//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthorizationResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthorizationResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CardReaderResult" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tokens" type="{http://www.opentravel.org/OTA/2003/05/beta}TokensType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="T3DS_Result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CAVV_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="T3DS_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PA_Request" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="IssuerURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CSC_Result" type="{http://www.opentravel.org/OTA/2003/05/beta}CSC_ResultType" minOccurs="0"/>
 *         &lt;element name="PIN_Result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="PIN_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PIN_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AVS_Result" type="{http://www.opentravel.org/OTA/2003/05/beta}AVS_ResultType" minOccurs="0"/>
 *         &lt;element name="AuthResponseDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="AuthSrcCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AuthValidationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ProductID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AuthCharacteristicInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TokenizationResult" type="{http://www.opentravel.org/OTA/2003/05/beta}TokenizationResultType" minOccurs="0"/>
 *         &lt;element name="SupplierMessages" type="{http://www.opentravel.org/OTA/2003/05/beta}SupplierMessagesType"/>
 *         &lt;element name="LocalCardDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CardCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CardNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExpireDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReturnURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FulfillmentNotificationURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RedirectHTML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdditionalRemarks" type="{http://www.opentravel.org/OTA/2003/05/beta}RemarksType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ResponseCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ApprovalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ApprovedAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="AuthAmountSent" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="BonusAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SupplierTransID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SupplierResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MerchantAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CAVV_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AuthRemarks1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AuthRemarks2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DCC_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentConfirmInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FulfillmentNotificationInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PaymentRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorizationResultType", propOrder = {
    "cardReaderResult",
    "t3DSResult",
    "cscResult",
    "pinResult",
    "avsResult",
    "authResponseDetail",
    "tokenizationResult",
    "supplierMessages",
    "localCardDetail",
    "returnURL",
    "fulfillmentNotificationURL",
    "redirectHTML",
    "additionalRemarks"
})
public class AuthorizationResultType {

    @XmlElement(name = "CardReaderResult")
    protected AuthorizationResultType.CardReaderResult cardReaderResult;
    @XmlElement(name = "T3DS_Result")
    protected AuthorizationResultType.T3DSResult t3DSResult;
    @XmlElement(name = "CSC_Result")
    protected CSCResultType cscResult;
    @XmlElement(name = "PIN_Result")
    protected AuthorizationResultType.PINResult pinResult;
    @XmlElement(name = "AVS_Result")
    protected AVSResultType avsResult;
    @XmlElement(name = "AuthResponseDetail")
    protected AuthorizationResultType.AuthResponseDetail authResponseDetail;
    @XmlElement(name = "TokenizationResult")
    protected TokenizationResultType tokenizationResult;
    @XmlElement(name = "SupplierMessages", required = true)
    protected SupplierMessagesType supplierMessages;
    @XmlElement(name = "LocalCardDetail")
    protected AuthorizationResultType.LocalCardDetail localCardDetail;
    @XmlElement(name = "ReturnURL")
    protected String returnURL;
    @XmlElement(name = "FulfillmentNotificationURL")
    protected String fulfillmentNotificationURL;
    @XmlElement(name = "RedirectHTML")
    protected String redirectHTML;
    @XmlElement(name = "AdditionalRemarks", required = true)
    protected RemarksType additionalRemarks;
    @XmlAttribute(name = "ResponseCode", required = true)
    protected String responseCode;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "ApprovalCode")
    protected String approvalCode;
    @XmlAttribute(name = "ApprovedAmount")
    protected BigDecimal approvedAmount;
    @XmlAttribute(name = "AuthAmountSent")
    protected BigDecimal authAmountSent;
    @XmlAttribute(name = "BonusAmount")
    protected BigDecimal bonusAmount;
    @XmlAttribute(name = "SupplierID")
    protected String supplierID;
    @XmlAttribute(name = "SupplierTransID")
    protected String supplierTransID;
    @XmlAttribute(name = "SupplierResponseCode")
    protected String supplierResponseCode;
    @XmlAttribute(name = "MerchantAccountNumber")
    protected String merchantAccountNumber;
    @XmlAttribute(name = "CAVV_ResultCode")
    protected String cavvResultCode;
    @XmlAttribute(name = "AuthRemarks1")
    protected String authRemarks1;
    @XmlAttribute(name = "AuthRemarks2")
    protected String authRemarks2;
    @XmlAttribute(name = "DCC_Remarks")
    protected String dccRemarks;
    @XmlAttribute(name = "CurrencyCode")
    protected String currencyCode;
    @XmlAttribute(name = "PaymentConfirmInd")
    protected String paymentConfirmInd;
    @XmlAttribute(name = "FulfillmentNotificationInd")
    protected Boolean fulfillmentNotificationInd;
    @XmlAttribute(name = "PaymentRef")
    protected String paymentRef;

    /**
     * Gets the value of the cardReaderResult property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResultType.CardReaderResult }
     *     
     */
    public AuthorizationResultType.CardReaderResult getCardReaderResult() {
        return cardReaderResult;
    }

    /**
     * Sets the value of the cardReaderResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResultType.CardReaderResult }
     *     
     */
    public void setCardReaderResult(AuthorizationResultType.CardReaderResult value) {
        this.cardReaderResult = value;
    }

    /**
     * Gets the value of the t3DSResult property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResultType.T3DSResult }
     *     
     */
    public AuthorizationResultType.T3DSResult getT3DSResult() {
        return t3DSResult;
    }

    /**
     * Sets the value of the t3DSResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResultType.T3DSResult }
     *     
     */
    public void setT3DSResult(AuthorizationResultType.T3DSResult value) {
        this.t3DSResult = value;
    }

    /**
     * Gets the value of the cscResult property.
     * 
     * @return
     *     possible object is
     *     {@link CSCResultType }
     *     
     */
    public CSCResultType getCSCResult() {
        return cscResult;
    }

    /**
     * Sets the value of the cscResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSCResultType }
     *     
     */
    public void setCSCResult(CSCResultType value) {
        this.cscResult = value;
    }

    /**
     * Gets the value of the pinResult property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResultType.PINResult }
     *     
     */
    public AuthorizationResultType.PINResult getPINResult() {
        return pinResult;
    }

    /**
     * Sets the value of the pinResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResultType.PINResult }
     *     
     */
    public void setPINResult(AuthorizationResultType.PINResult value) {
        this.pinResult = value;
    }

    /**
     * Gets the value of the avsResult property.
     * 
     * @return
     *     possible object is
     *     {@link AVSResultType }
     *     
     */
    public AVSResultType getAVSResult() {
        return avsResult;
    }

    /**
     * Sets the value of the avsResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AVSResultType }
     *     
     */
    public void setAVSResult(AVSResultType value) {
        this.avsResult = value;
    }

    /**
     * Gets the value of the authResponseDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResultType.AuthResponseDetail }
     *     
     */
    public AuthorizationResultType.AuthResponseDetail getAuthResponseDetail() {
        return authResponseDetail;
    }

    /**
     * Sets the value of the authResponseDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResultType.AuthResponseDetail }
     *     
     */
    public void setAuthResponseDetail(AuthorizationResultType.AuthResponseDetail value) {
        this.authResponseDetail = value;
    }

    /**
     * Gets the value of the tokenizationResult property.
     * 
     * @return
     *     possible object is
     *     {@link TokenizationResultType }
     *     
     */
    public TokenizationResultType getTokenizationResult() {
        return tokenizationResult;
    }

    /**
     * Sets the value of the tokenizationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenizationResultType }
     *     
     */
    public void setTokenizationResult(TokenizationResultType value) {
        this.tokenizationResult = value;
    }

    /**
     * Gets the value of the supplierMessages property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierMessagesType }
     *     
     */
    public SupplierMessagesType getSupplierMessages() {
        return supplierMessages;
    }

    /**
     * Sets the value of the supplierMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierMessagesType }
     *     
     */
    public void setSupplierMessages(SupplierMessagesType value) {
        this.supplierMessages = value;
    }

    /**
     * Gets the value of the localCardDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResultType.LocalCardDetail }
     *     
     */
    public AuthorizationResultType.LocalCardDetail getLocalCardDetail() {
        return localCardDetail;
    }

    /**
     * Sets the value of the localCardDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResultType.LocalCardDetail }
     *     
     */
    public void setLocalCardDetail(AuthorizationResultType.LocalCardDetail value) {
        this.localCardDetail = value;
    }

    /**
     * Gets the value of the returnURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnURL() {
        return returnURL;
    }

    /**
     * Sets the value of the returnURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnURL(String value) {
        this.returnURL = value;
    }

    /**
     * Gets the value of the fulfillmentNotificationURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentNotificationURL() {
        return fulfillmentNotificationURL;
    }

    /**
     * Sets the value of the fulfillmentNotificationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentNotificationURL(String value) {
        this.fulfillmentNotificationURL = value;
    }

    /**
     * Gets the value of the redirectHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedirectHTML() {
        return redirectHTML;
    }

    /**
     * Sets the value of the redirectHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedirectHTML(String value) {
        this.redirectHTML = value;
    }

    /**
     * Gets the value of the additionalRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link RemarksType }
     *     
     */
    public RemarksType getAdditionalRemarks() {
        return additionalRemarks;
    }

    /**
     * Sets the value of the additionalRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemarksType }
     *     
     */
    public void setAdditionalRemarks(RemarksType value) {
        this.additionalRemarks = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the approvalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalCode() {
        return approvalCode;
    }

    /**
     * Sets the value of the approvalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalCode(String value) {
        this.approvalCode = value;
    }

    /**
     * Gets the value of the approvedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApprovedAmount() {
        return approvedAmount;
    }

    /**
     * Sets the value of the approvedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApprovedAmount(BigDecimal value) {
        this.approvedAmount = value;
    }

    /**
     * Gets the value of the authAmountSent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAuthAmountSent() {
        return authAmountSent;
    }

    /**
     * Sets the value of the authAmountSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAuthAmountSent(BigDecimal value) {
        this.authAmountSent = value;
    }

    /**
     * Gets the value of the bonusAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusAmount() {
        return bonusAmount;
    }

    /**
     * Sets the value of the bonusAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusAmount(BigDecimal value) {
        this.bonusAmount = value;
    }

    /**
     * Gets the value of the supplierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierID() {
        return supplierID;
    }

    /**
     * Sets the value of the supplierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierID(String value) {
        this.supplierID = value;
    }

    /**
     * Gets the value of the supplierTransID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierTransID() {
        return supplierTransID;
    }

    /**
     * Sets the value of the supplierTransID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierTransID(String value) {
        this.supplierTransID = value;
    }

    /**
     * Gets the value of the supplierResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierResponseCode() {
        return supplierResponseCode;
    }

    /**
     * Sets the value of the supplierResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierResponseCode(String value) {
        this.supplierResponseCode = value;
    }

    /**
     * Gets the value of the merchantAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAccountNumber() {
        return merchantAccountNumber;
    }

    /**
     * Sets the value of the merchantAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAccountNumber(String value) {
        this.merchantAccountNumber = value;
    }

    /**
     * Gets the value of the cavvResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAVVResultCode() {
        return cavvResultCode;
    }

    /**
     * Sets the value of the cavvResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAVVResultCode(String value) {
        this.cavvResultCode = value;
    }

    /**
     * Gets the value of the authRemarks1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthRemarks1() {
        return authRemarks1;
    }

    /**
     * Sets the value of the authRemarks1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthRemarks1(String value) {
        this.authRemarks1 = value;
    }

    /**
     * Gets the value of the authRemarks2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthRemarks2() {
        return authRemarks2;
    }

    /**
     * Sets the value of the authRemarks2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthRemarks2(String value) {
        this.authRemarks2 = value;
    }

    /**
     * Gets the value of the dccRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCCRemarks() {
        return dccRemarks;
    }

    /**
     * Sets the value of the dccRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCCRemarks(String value) {
        this.dccRemarks = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the paymentConfirmInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentConfirmInd() {
        return paymentConfirmInd;
    }

    /**
     * Sets the value of the paymentConfirmInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentConfirmInd(String value) {
        this.paymentConfirmInd = value;
    }

    /**
     * Gets the value of the fulfillmentNotificationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFulfillmentNotificationInd() {
        return fulfillmentNotificationInd;
    }

    /**
     * Sets the value of the fulfillmentNotificationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFulfillmentNotificationInd(Boolean value) {
        this.fulfillmentNotificationInd = value;
    }

    /**
     * Gets the value of the paymentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRef() {
        return paymentRef;
    }

    /**
     * Sets the value of the paymentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRef(String value) {
        this.paymentRef = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="AuthSrcCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AuthValidationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ProductID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AuthCharacteristicInd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AuthResponseDetail {

        @XmlAttribute(name = "AuthSrcCode")
        protected String authSrcCode;
        @XmlAttribute(name = "AuthValidationCode")
        protected String authValidationCode;
        @XmlAttribute(name = "ProductID")
        protected String productID;
        @XmlAttribute(name = "AuthCharacteristicInd")
        protected String authCharacteristicInd;

        /**
         * Gets the value of the authSrcCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthSrcCode() {
            return authSrcCode;
        }

        /**
         * Sets the value of the authSrcCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthSrcCode(String value) {
            this.authSrcCode = value;
        }

        /**
         * Gets the value of the authValidationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthValidationCode() {
            return authValidationCode;
        }

        /**
         * Sets the value of the authValidationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthValidationCode(String value) {
            this.authValidationCode = value;
        }

        /**
         * Gets the value of the productID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductID() {
            return productID;
        }

        /**
         * Sets the value of the productID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductID(String value) {
            this.productID = value;
        }

        /**
         * Gets the value of the authCharacteristicInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthCharacteristicInd() {
            return authCharacteristicInd;
        }

        /**
         * Sets the value of the authCharacteristicInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthCharacteristicInd(String value) {
            this.authCharacteristicInd = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tokens" type="{http://www.opentravel.org/OTA/2003/05/beta}TokensType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tokens"
    })
    public static class CardReaderResult {

        @XmlElement(name = "Tokens")
        protected TokensType tokens;
        @XmlAttribute(name = "ResultCode")
        protected String resultCode;
        @XmlAttribute(name = "Remarks")
        protected String remarks;

        /**
         * Gets the value of the tokens property.
         * 
         * @return
         *     possible object is
         *     {@link TokensType }
         *     
         */
        public TokensType getTokens() {
            return tokens;
        }

        /**
         * Sets the value of the tokens property.
         * 
         * @param value
         *     allowed object is
         *     {@link TokensType }
         *     
         */
        public void setTokens(TokensType value) {
            this.tokens = value;
        }

        /**
         * Gets the value of the resultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultCode() {
            return resultCode;
        }

        /**
         * Sets the value of the resultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultCode(String value) {
            this.resultCode = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CardCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CardNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExpireDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LocalCardDetail {

        @XmlAttribute(name = "CardCode", required = true)
        protected String cardCode;
        @XmlAttribute(name = "CardNumber", required = true)
        protected String cardNumber;
        @XmlAttribute(name = "ExpireDate", required = true)
        protected String expireDate;
        @XmlAttribute(name = "Description")
        protected String description;

        /**
         * Gets the value of the cardCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardCode() {
            return cardCode;
        }

        /**
         * Sets the value of the cardCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardCode(String value) {
            this.cardCode = value;
        }

        /**
         * Gets the value of the cardNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardNumber() {
            return cardNumber;
        }

        /**
         * Sets the value of the cardNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardNumber(String value) {
            this.cardNumber = value;
        }

        /**
         * Gets the value of the expireDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpireDate() {
            return expireDate;
        }

        /**
         * Sets the value of the expireDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpireDate(String value) {
            this.expireDate = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="PIN_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PIN_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PINResult {

        @XmlAttribute(name = "PIN_ResultCode")
        protected String pinResultCode;
        @XmlAttribute(name = "PIN_Remarks")
        protected String pinRemarks;

        /**
         * Gets the value of the pinResultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPINResultCode() {
            return pinResultCode;
        }

        /**
         * Sets the value of the pinResultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPINResultCode(String value) {
            this.pinResultCode = value;
        }

        /**
         * Gets the value of the pinRemarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPINRemarks() {
            return pinRemarks;
        }

        /**
         * Sets the value of the pinRemarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPINRemarks(String value) {
            this.pinRemarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CAVV_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="T3DS_Remarks" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PA_Request" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="IssuerURL" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class T3DSResult {

        @XmlAttribute(name = "CAVV_ResultCode")
        protected String cavvResultCode;
        @XmlAttribute(name = "T3DS_Remarks")
        protected String t3DSRemarks;
        @XmlAttribute(name = "PA_Request")
        protected String paRequest;
        @XmlAttribute(name = "IssuerURL")
        protected String issuerURL;
        @XmlAttribute(name = "MD")
        protected String md;

        /**
         * Gets the value of the cavvResultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVVResultCode() {
            return cavvResultCode;
        }

        /**
         * Sets the value of the cavvResultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVVResultCode(String value) {
            this.cavvResultCode = value;
        }

        /**
         * Gets the value of the t3DSRemarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getT3DSRemarks() {
            return t3DSRemarks;
        }

        /**
         * Sets the value of the t3DSRemarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setT3DSRemarks(String value) {
            this.t3DSRemarks = value;
        }

        /**
         * Gets the value of the paRequest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPARequest() {
            return paRequest;
        }

        /**
         * Sets the value of the paRequest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPARequest(String value) {
            this.paRequest = value;
        }

        /**
         * Gets the value of the issuerURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuerURL() {
            return issuerURL;
        }

        /**
         * Sets the value of the issuerURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuerURL(String value) {
            this.issuerURL = value;
        }

        /**
         * Gets the value of the md property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMD() {
            return md;
        }

        /**
         * Sets the value of the md property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMD(String value) {
            this.md = value;
        }

    }

}
