//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CarRentalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarRentalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pickup">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PickupAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="PickupDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Return">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ReturnAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ReturnDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Renter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProviderInfo" type="{http://www.opentravel.org/OTA/2003/05/beta}ProviderInfoType"/>
 *         &lt;element name="Cost" type="{http://www.opentravel.org/OTA/2003/05/beta}CostType"/>
 *         &lt;element name="PaymentInfo" type="{http://www.opentravel.org/OTA/2003/05/beta}PaymentInfoType" minOccurs="0"/>
 *         &lt;element name="ServiceNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AgreementNbr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReferenceNbr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VehicleClassID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Distance" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DistanceUnit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarRentalType", propOrder = {
    "pickup",
    "_return",
    "renter",
    "providerInfo",
    "cost",
    "paymentInfo",
    "serviceNote"
})
public class CarRentalType {

    @XmlElement(name = "Pickup", required = true)
    protected CarRentalType.Pickup pickup;
    @XmlElement(name = "Return", required = true)
    protected CarRentalType.Return _return;
    @XmlElement(name = "Renter", required = true)
    protected CarRentalType.Renter renter;
    @XmlElement(name = "ProviderInfo", required = true)
    protected ProviderInfoType providerInfo;
    @XmlElement(name = "Cost", required = true)
    protected CostType cost;
    @XmlElement(name = "PaymentInfo")
    protected PaymentInfoType paymentInfo;
    @XmlElement(name = "ServiceNote")
    protected String serviceNote;
    @XmlAttribute(name = "AgreementNbr", required = true)
    protected String agreementNbr;
    @XmlAttribute(name = "ReferenceNbr", required = true)
    protected String referenceNbr;
    @XmlAttribute(name = "VehicleClassID")
    protected String vehicleClassID;
    @XmlAttribute(name = "Distance")
    protected Integer distance;
    @XmlAttribute(name = "DistanceUnit")
    protected String distanceUnit;

    /**
     * Gets the value of the pickup property.
     * 
     * @return
     *     possible object is
     *     {@link CarRentalType.Pickup }
     *     
     */
    public CarRentalType.Pickup getPickup() {
        return pickup;
    }

    /**
     * Sets the value of the pickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarRentalType.Pickup }
     *     
     */
    public void setPickup(CarRentalType.Pickup value) {
        this.pickup = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link CarRentalType.Return }
     *     
     */
    public CarRentalType.Return getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarRentalType.Return }
     *     
     */
    public void setReturn(CarRentalType.Return value) {
        this._return = value;
    }

    /**
     * Gets the value of the renter property.
     * 
     * @return
     *     possible object is
     *     {@link CarRentalType.Renter }
     *     
     */
    public CarRentalType.Renter getRenter() {
        return renter;
    }

    /**
     * Sets the value of the renter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarRentalType.Renter }
     *     
     */
    public void setRenter(CarRentalType.Renter value) {
        this.renter = value;
    }

    /**
     * Gets the value of the providerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderInfoType }
     *     
     */
    public ProviderInfoType getProviderInfo() {
        return providerInfo;
    }

    /**
     * Sets the value of the providerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderInfoType }
     *     
     */
    public void setProviderInfo(ProviderInfoType value) {
        this.providerInfo = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link CostType }
     *     
     */
    public CostType getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostType }
     *     
     */
    public void setCost(CostType value) {
        this.cost = value;
    }

    /**
     * Gets the value of the paymentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInfoType }
     *     
     */
    public PaymentInfoType getPaymentInfo() {
        return paymentInfo;
    }

    /**
     * Sets the value of the paymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInfoType }
     *     
     */
    public void setPaymentInfo(PaymentInfoType value) {
        this.paymentInfo = value;
    }

    /**
     * Gets the value of the serviceNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceNote() {
        return serviceNote;
    }

    /**
     * Sets the value of the serviceNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceNote(String value) {
        this.serviceNote = value;
    }

    /**
     * Gets the value of the agreementNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementNbr() {
        return agreementNbr;
    }

    /**
     * Sets the value of the agreementNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementNbr(String value) {
        this.agreementNbr = value;
    }

    /**
     * Gets the value of the referenceNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNbr() {
        return referenceNbr;
    }

    /**
     * Sets the value of the referenceNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNbr(String value) {
        this.referenceNbr = value;
    }

    /**
     * Gets the value of the vehicleClassID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleClassID() {
        return vehicleClassID;
    }

    /**
     * Sets the value of the vehicleClassID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleClassID(String value) {
        this.vehicleClassID = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDistance(Integer value) {
        this.distance = value;
    }

    /**
     * Gets the value of the distanceUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistanceUnit() {
        return distanceUnit;
    }

    /**
     * Sets the value of the distanceUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistanceUnit(String value) {
        this.distanceUnit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PickupAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="PickupDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pickupAddress"
    })
    public static class Pickup {

        @XmlElement(name = "PickupAddress", required = true)
        protected AddressType pickupAddress;
        @XmlAttribute(name = "PickupDateTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar pickupDateTime;

        /**
         * Gets the value of the pickupAddress property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getPickupAddress() {
            return pickupAddress;
        }

        /**
         * Sets the value of the pickupAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setPickupAddress(AddressType value) {
            this.pickupAddress = value;
        }

        /**
         * Gets the value of the pickupDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPickupDateTime() {
            return pickupDateTime;
        }

        /**
         * Sets the value of the pickupDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPickupDateTime(XMLGregorianCalendar value) {
            this.pickupDateTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Renter {

        @XmlAttribute(name = "Name")
        protected String name;
        @XmlAttribute(name = "FirstName")
        protected String firstName;
        @XmlAttribute(name = "LastName")
        protected String lastName;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ReturnAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ReturnDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnAddress"
    })
    public static class Return {

        @XmlElement(name = "ReturnAddress", required = true)
        protected AddressType returnAddress;
        @XmlAttribute(name = "ReturnDateTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar returnDateTime;

        /**
         * Gets the value of the returnAddress property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getReturnAddress() {
            return returnAddress;
        }

        /**
         * Sets the value of the returnAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setReturnAddress(AddressType value) {
            this.returnAddress = value;
        }

        /**
         * Gets the value of the returnDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReturnDateTime() {
            return returnDateTime;
        }

        /**
         * Sets the value of the returnDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReturnDateTime(XMLGregorianCalendar value) {
            this.returnDateTime = value;
        }

    }

}
