//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Dynamic Currency Conversion
 * 
 * <p>Java class for DCCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCCType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DCC_TransID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OptedIn" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCCType")
public class DCCType {

    @XmlAttribute(name = "DCC_TransID", required = true)
    protected String dccTransID;
    @XmlAttribute(name = "OptedIn")
    protected Boolean optedIn;

    /**
     * Gets the value of the dccTransID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCCTransID() {
        return dccTransID;
    }

    /**
     * Sets the value of the dccTransID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCCTransID(String value) {
        this.dccTransID = value;
    }

    /**
     * Gets the value of the optedIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptedIn() {
        return optedIn;
    }

    /**
     * Sets the value of the optedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptedIn(Boolean value) {
        this.optedIn = value;
    }

}
