//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Document detail
 * 
 * <p>Java class for DocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FOP_Amount" type="{http://www.opentravel.org/OTA/2003/05/beta}FOP_FareBreakType" maxOccurs="20" minOccurs="0"/>
 *         &lt;element name="TaxBreak" type="{http://www.opentravel.org/OTA/2003/05/beta}TaxType" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="FeeBreak" type="{http://www.opentravel.org/OTA/2003/05/beta}FeeType" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="MiscItem" type="{http://www.opentravel.org/OTA/2003/05/beta}MiscItemType" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="FareCalc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EMD_CouponDetail" maxOccurs="99" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fare" type="{http://www.opentravel.org/OTA/2003/05/beta}FareBreakType" minOccurs="0"/>
 *                   &lt;element name="TaxBreak" type="{http://www.opentravel.org/OTA/2003/05/beta}TaxType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="RFIC_SubCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AssociatedDocNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AssociatedSegmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ConsumedAtIssuanceInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="DocType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DocStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssueLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssueDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="eTicketInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="NetFareInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DocNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CouponNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BaseFare" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="NetFare" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="Taxes" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="Fees" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *       &lt;attribute name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FlightDetailIndex" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="InitialDocNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InitialDocType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AssociatedDocNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DocSubType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RFI_Code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", propOrder = {
    "fopAmount",
    "taxBreak",
    "feeBreak",
    "miscItem",
    "fareCalc",
    "emdCouponDetail"
})
@XmlSeeAlso({
    com.sabre.hospitality.domain.payments.v300.PassengerDetailType.Document.class
})
public class DocumentType {

    @XmlElement(name = "FOP_Amount")
    protected List<FOPFareBreakType> fopAmount;
    @XmlElement(name = "TaxBreak")
    protected List<TaxType> taxBreak;
    @XmlElement(name = "FeeBreak")
    protected List<FeeType> feeBreak;
    @XmlElement(name = "MiscItem")
    protected List<MiscItemType> miscItem;
    @XmlElement(name = "FareCalc")
    protected String fareCalc;
    @XmlElement(name = "EMD_CouponDetail")
    protected List<DocumentType.EMDCouponDetail> emdCouponDetail;
    @XmlAttribute(name = "DocType", required = true)
    protected String docType;
    @XmlAttribute(name = "DocStatus")
    protected String docStatus;
    @XmlAttribute(name = "IssueLocation")
    protected String issueLocation;
    @XmlAttribute(name = "IssueDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueDateTime;
    @XmlAttribute(name = "eTicketInd")
    protected Boolean eTicketInd;
    @XmlAttribute(name = "NetFareInd")
    protected Boolean netFareInd;
    @XmlAttribute(name = "DocNumber")
    protected String docNumber;
    @XmlAttribute(name = "CouponNumber")
    protected String couponNumber;
    @XmlAttribute(name = "BaseFare")
    protected BigDecimal baseFare;
    @XmlAttribute(name = "NetFare")
    protected BigDecimal netFare;
    @XmlAttribute(name = "Taxes")
    protected BigDecimal taxes;
    @XmlAttribute(name = "Fees")
    protected BigDecimal fees;
    @XmlAttribute(name = "Points")
    protected BigInteger points;
    @XmlAttribute(name = "CategoryCode")
    protected String categoryCode;
    @XmlAttribute(name = "FlightDetailIndex")
    protected BigInteger flightDetailIndex;
    @XmlAttribute(name = "InitialDocNumber")
    protected String initialDocNumber;
    @XmlAttribute(name = "InitialDocType", required = true)
    protected String initialDocType;
    @XmlAttribute(name = "AssociatedDocNumber")
    protected String associatedDocNumber;
    @XmlAttribute(name = "DocSubType")
    protected String docSubType;
    @XmlAttribute(name = "RFI_Code")
    protected String rfiCode;

    /**
     * Gets the value of the fopAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fopAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFOPAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FOPFareBreakType }
     * 
     * 
     */
    public List<FOPFareBreakType> getFOPAmount() {
        if (fopAmount == null) {
            fopAmount = new ArrayList<FOPFareBreakType>();
        }
        return this.fopAmount;
    }

    /**
     * Gets the value of the taxBreak property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxBreak property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxBreak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxType }
     * 
     * 
     */
    public List<TaxType> getTaxBreak() {
        if (taxBreak == null) {
            taxBreak = new ArrayList<TaxType>();
        }
        return this.taxBreak;
    }

    /**
     * Gets the value of the feeBreak property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feeBreak property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeeBreak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeeType }
     * 
     * 
     */
    public List<FeeType> getFeeBreak() {
        if (feeBreak == null) {
            feeBreak = new ArrayList<FeeType>();
        }
        return this.feeBreak;
    }

    /**
     * Gets the value of the miscItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MiscItemType }
     * 
     * 
     */
    public List<MiscItemType> getMiscItem() {
        if (miscItem == null) {
            miscItem = new ArrayList<MiscItemType>();
        }
        return this.miscItem;
    }

    /**
     * Gets the value of the fareCalc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareCalc() {
        return fareCalc;
    }

    /**
     * Sets the value of the fareCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareCalc(String value) {
        this.fareCalc = value;
    }

    /**
     * Gets the value of the emdCouponDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emdCouponDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMDCouponDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType.EMDCouponDetail }
     * 
     * 
     */
    public List<DocumentType.EMDCouponDetail> getEMDCouponDetail() {
        if (emdCouponDetail == null) {
            emdCouponDetail = new ArrayList<DocumentType.EMDCouponDetail>();
        }
        return this.emdCouponDetail;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocType(String value) {
        this.docType = value;
    }

    /**
     * Gets the value of the docStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocStatus() {
        return docStatus;
    }

    /**
     * Sets the value of the docStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocStatus(String value) {
        this.docStatus = value;
    }

    /**
     * Gets the value of the issueLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueLocation() {
        return issueLocation;
    }

    /**
     * Sets the value of the issueLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueLocation(String value) {
        this.issueLocation = value;
    }

    /**
     * Gets the value of the issueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDateTime() {
        return issueDateTime;
    }

    /**
     * Sets the value of the issueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDateTime(XMLGregorianCalendar value) {
        this.issueDateTime = value;
    }

    /**
     * Gets the value of the eTicketInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isETicketInd() {
        return eTicketInd;
    }

    /**
     * Sets the value of the eTicketInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setETicketInd(Boolean value) {
        this.eTicketInd = value;
    }

    /**
     * Gets the value of the netFareInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNetFareInd() {
        return netFareInd;
    }

    /**
     * Sets the value of the netFareInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNetFareInd(Boolean value) {
        this.netFareInd = value;
    }

    /**
     * Gets the value of the docNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the couponNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponNumber() {
        return couponNumber;
    }

    /**
     * Sets the value of the couponNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponNumber(String value) {
        this.couponNumber = value;
    }

    /**
     * Gets the value of the baseFare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseFare() {
        return baseFare;
    }

    /**
     * Sets the value of the baseFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseFare(BigDecimal value) {
        this.baseFare = value;
    }

    /**
     * Gets the value of the netFare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetFare() {
        return netFare;
    }

    /**
     * Sets the value of the netFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetFare(BigDecimal value) {
        this.netFare = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxes(BigDecimal value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFees(BigDecimal value) {
        this.fees = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoints(BigInteger value) {
        this.points = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the flightDetailIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlightDetailIndex() {
        return flightDetailIndex;
    }

    /**
     * Sets the value of the flightDetailIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlightDetailIndex(BigInteger value) {
        this.flightDetailIndex = value;
    }

    /**
     * Gets the value of the initialDocNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialDocNumber() {
        return initialDocNumber;
    }

    /**
     * Sets the value of the initialDocNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialDocNumber(String value) {
        this.initialDocNumber = value;
    }

    /**
     * Gets the value of the initialDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialDocType() {
        return initialDocType;
    }

    /**
     * Sets the value of the initialDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialDocType(String value) {
        this.initialDocType = value;
    }

    /**
     * Gets the value of the associatedDocNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedDocNumber() {
        return associatedDocNumber;
    }

    /**
     * Sets the value of the associatedDocNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedDocNumber(String value) {
        this.associatedDocNumber = value;
    }

    /**
     * Gets the value of the docSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocSubType() {
        return docSubType;
    }

    /**
     * Sets the value of the docSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocSubType(String value) {
        this.docSubType = value;
    }

    /**
     * Gets the value of the rfiCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFICode() {
        return rfiCode;
    }

    /**
     * Sets the value of the rfiCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFICode(String value) {
        this.rfiCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fare" type="{http://www.opentravel.org/OTA/2003/05/beta}FareBreakType" minOccurs="0"/>
     *         &lt;element name="TaxBreak" type="{http://www.opentravel.org/OTA/2003/05/beta}TaxType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="RFIC_SubCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AssociatedDocNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AssociatedSegmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ConsumedAtIssuanceInd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fare",
        "taxBreak",
        "remarks"
    })
    public static class EMDCouponDetail {

        @XmlElement(name = "Fare")
        protected FareBreakType fare;
        @XmlElement(name = "TaxBreak")
        protected List<TaxType> taxBreak;
        @XmlElement(name = "Remarks")
        protected String remarks;
        @XmlAttribute(name = "RFIC_SubCode")
        protected String rficSubCode;
        @XmlAttribute(name = "AssociatedDocNumber")
        protected String associatedDocNumber;
        @XmlAttribute(name = "AssociatedSegmentNumber")
        protected String associatedSegmentNumber;
        @XmlAttribute(name = "ConsumedAtIssuanceInd")
        protected String consumedAtIssuanceInd;
        @XmlAttribute(name = "Quantity")
        protected Integer quantity;

        /**
         * Gets the value of the fare property.
         * 
         * @return
         *     possible object is
         *     {@link FareBreakType }
         *     
         */
        public FareBreakType getFare() {
            return fare;
        }

        /**
         * Sets the value of the fare property.
         * 
         * @param value
         *     allowed object is
         *     {@link FareBreakType }
         *     
         */
        public void setFare(FareBreakType value) {
            this.fare = value;
        }

        /**
         * Gets the value of the taxBreak property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taxBreak property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaxBreak().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TaxType }
         * 
         * 
         */
        public List<TaxType> getTaxBreak() {
            if (taxBreak == null) {
                taxBreak = new ArrayList<TaxType>();
            }
            return this.taxBreak;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the rficSubCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFICSubCode() {
            return rficSubCode;
        }

        /**
         * Sets the value of the rficSubCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFICSubCode(String value) {
            this.rficSubCode = value;
        }

        /**
         * Gets the value of the associatedDocNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssociatedDocNumber() {
            return associatedDocNumber;
        }

        /**
         * Sets the value of the associatedDocNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssociatedDocNumber(String value) {
            this.associatedDocNumber = value;
        }

        /**
         * Gets the value of the associatedSegmentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssociatedSegmentNumber() {
            return associatedSegmentNumber;
        }

        /**
         * Sets the value of the associatedSegmentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssociatedSegmentNumber(String value) {
            this.associatedSegmentNumber = value;
        }

        /**
         * Gets the value of the consumedAtIssuanceInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsumedAtIssuanceInd() {
            return consumedAtIssuanceInd;
        }

        /**
         * Sets the value of the consumedAtIssuanceInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsumedAtIssuanceInd(String value) {
            this.consumedAtIssuanceInd = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setQuantity(Integer value) {
            this.quantity = value;
        }

    }

}
