//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.hospitality.domain.payments.v300 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TPAExtensions_QNAME = new QName("http://www.opentravel.org/OTA/2003/05/beta", "TPA_Extensions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.hospitality.domain.payments.v300
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaymentRQ }
     * 
     */
    public PaymentRQ createPaymentRQ() {
        return new PaymentRQ();
    }

    /**
     * Create an instance of {@link PaymentRS }
     * 
     */
    public PaymentRS createPaymentRS() {
        return new PaymentRS();
    }

    /**
     * Create an instance of {@link TokensType }
     * 
     */
    public TokensType createTokensType() {
        return new TokensType();
    }

    /**
     * Create an instance of {@link CarRentalType }
     * 
     */
    public CarRentalType createCarRentalType() {
        return new CarRentalType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link PersonIDType }
     * 
     */
    public PersonIDType createPersonIDType() {
        return new PersonIDType();
    }

    /**
     * Create an instance of {@link PassengerDetailType }
     * 
     */
    public PassengerDetailType createPassengerDetailType() {
        return new PassengerDetailType();
    }

    /**
     * Create an instance of {@link FlightDetailType }
     * 
     */
    public FlightDetailType createFlightDetailType() {
        return new FlightDetailType();
    }

    /**
     * Create an instance of {@link PaymentCardType }
     * 
     */
    public PaymentCardType createPaymentCardType() {
        return new PaymentCardType();
    }

    /**
     * Create an instance of {@link RailJourneyType }
     * 
     */
    public RailJourneyType createRailJourneyType() {
        return new RailJourneyType();
    }

    /**
     * Create an instance of {@link PaymentRS.NotificationList }
     * 
     */
    public PaymentRS.NotificationList createPaymentRSNotificationList() {
        return new PaymentRS.NotificationList();
    }

    /**
     * Create an instance of {@link PaymentRS.AccountDetail }
     * 
     */
    public PaymentRS.AccountDetail createPaymentRSAccountDetail() {
        return new PaymentRS.AccountDetail();
    }

    /**
     * Create an instance of {@link AuthorizationResultType }
     * 
     */
    public AuthorizationResultType createAuthorizationResultType() {
        return new AuthorizationResultType();
    }

    /**
     * Create an instance of {@link PaymentRS.Results }
     * 
     */
    public PaymentRS.Results createPaymentRSResults() {
        return new PaymentRS.Results();
    }

    /**
     * Create an instance of {@link PaymentDetailType }
     * 
     */
    public PaymentDetailType createPaymentDetailType() {
        return new PaymentDetailType();
    }

    /**
     * Create an instance of {@link POSType }
     * 
     */
    public POSType createPOSType() {
        return new POSType();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail }
     * 
     */
    public POSType.BrowserDetail createPOSTypeBrowserDetail() {
        return new POSType.BrowserDetail();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail.HttpHeaders }
     * 
     */
    public POSType.BrowserDetail.HttpHeaders createPOSTypeBrowserDetailHttpHeaders() {
        return new POSType.BrowserDetail.HttpHeaders();
    }

    /**
     * Create an instance of {@link TPAExtensionsType }
     * 
     */
    public TPAExtensionsType createTPAExtensionsType() {
        return new TPAExtensionsType();
    }

    /**
     * Create an instance of {@link PaymentRQ.Action }
     * 
     */
    public PaymentRQ.Action createPaymentRQAction() {
        return new PaymentRQ.Action();
    }

    /**
     * Create an instance of {@link PaymentRQ.ServiceIndicator }
     * 
     */
    public PaymentRQ.ServiceIndicator createPaymentRQServiceIndicator() {
        return new PaymentRQ.ServiceIndicator();
    }

    /**
     * Create an instance of {@link MerchantDetailType }
     * 
     */
    public MerchantDetailType createMerchantDetailType() {
        return new MerchantDetailType();
    }

    /**
     * Create an instance of {@link PaymentRQ.OrderDetail }
     * 
     */
    public PaymentRQ.OrderDetail createPaymentRQOrderDetail() {
        return new PaymentRQ.OrderDetail();
    }

    /**
     * Create an instance of {@link AccountDetailType }
     * 
     */
    public AccountDetailType createAccountDetailType() {
        return new AccountDetailType();
    }

    /**
     * Create an instance of {@link PaymentRQ.CustomerDetail }
     * 
     */
    public PaymentRQ.CustomerDetail createPaymentRQCustomerDetail() {
        return new PaymentRQ.CustomerDetail();
    }

    /**
     * Create an instance of {@link PaymentRS.OrderDetail }
     * 
     */
    public PaymentRS.OrderDetail createPaymentRSOrderDetail() {
        return new PaymentRS.OrderDetail();
    }

    /**
     * Create an instance of {@link PaymentRS.Result }
     * 
     */
    public PaymentRS.Result createPaymentRSResult() {
        return new PaymentRS.Result();
    }

    /**
     * Create an instance of {@link PaymentRS.BalanceInquiryResult }
     * 
     */
    public PaymentRS.BalanceInquiryResult createPaymentRSBalanceInquiryResult() {
        return new PaymentRS.BalanceInquiryResult();
    }

    /**
     * Create an instance of {@link PaymentRS.VerificationResult }
     * 
     */
    public PaymentRS.VerificationResult createPaymentRSVerificationResult() {
        return new PaymentRS.VerificationResult();
    }

    /**
     * Create an instance of {@link PaymentRS.DCCResult }
     * 
     */
    public PaymentRS.DCCResult createPaymentRSDCCResult() {
        return new PaymentRS.DCCResult();
    }

    /**
     * Create an instance of {@link PaymentRS.AccountValidationResult }
     * 
     */
    public PaymentRS.AccountValidationResult createPaymentRSAccountValidationResult() {
        return new PaymentRS.AccountValidationResult();
    }

    /**
     * Create an instance of {@link ConfirmAuthResultType }
     * 
     */
    public ConfirmAuthResultType createConfirmAuthResultType() {
        return new ConfirmAuthResultType();
    }

    /**
     * Create an instance of {@link CancelAuthResultType }
     * 
     */
    public CancelAuthResultType createCancelAuthResultType() {
        return new CancelAuthResultType();
    }

    /**
     * Create an instance of {@link RefundResultType }
     * 
     */
    public RefundResultType createRefundResultType() {
        return new RefundResultType();
    }

    /**
     * Create an instance of {@link PaymentRS.GetCardResult }
     * 
     */
    public PaymentRS.GetCardResult createPaymentRSGetCardResult() {
        return new PaymentRS.GetCardResult();
    }

    /**
     * Create an instance of {@link PaymentRS.QueryDeferredPaymentResult }
     * 
     */
    public PaymentRS.QueryDeferredPaymentResult createPaymentRSQueryDeferredPaymentResult() {
        return new PaymentRS.QueryDeferredPaymentResult();
    }

    /**
     * Create an instance of {@link PaymentRS.CaptureResult }
     * 
     */
    public PaymentRS.CaptureResult createPaymentRSCaptureResult() {
        return new PaymentRS.CaptureResult();
    }

    /**
     * Create an instance of {@link PaymentRS.FraudScreenResult }
     * 
     */
    public PaymentRS.FraudScreenResult createPaymentRSFraudScreenResult() {
        return new PaymentRS.FraudScreenResult();
    }

    /**
     * Create an instance of {@link PaymentRS.FraudRemarks }
     * 
     */
    public PaymentRS.FraudRemarks createPaymentRSFraudRemarks() {
        return new PaymentRS.FraudRemarks();
    }

    /**
     * Create an instance of {@link TokenizationResultType }
     * 
     */
    public TokenizationResultType createTokenizationResultType() {
        return new TokenizationResultType();
    }

    /**
     * Create an instance of {@link RemarksType }
     * 
     */
    public RemarksType createRemarksType() {
        return new RemarksType();
    }

    /**
     * Create an instance of {@link FOPFareBreakType }
     * 
     */
    public FOPFareBreakType createFOPFareBreakType() {
        return new FOPFareBreakType();
    }

    /**
     * Create an instance of {@link StreetNmbrType }
     * 
     */
    public StreetNmbrType createStreetNmbrType() {
        return new StreetNmbrType();
    }

    /**
     * Create an instance of {@link GetCardResultType }
     * 
     */
    public GetCardResultType createGetCardResultType() {
        return new GetCardResultType();
    }

    /**
     * Create an instance of {@link StateProvType }
     * 
     */
    public StateProvType createStateProvType() {
        return new StateProvType();
    }

    /**
     * Create an instance of {@link GuestType }
     * 
     */
    public GuestType createGuestType() {
        return new GuestType();
    }

    /**
     * Create an instance of {@link CSCResultType }
     * 
     */
    public CSCResultType createCSCResultType() {
        return new CSCResultType();
    }

    /**
     * Create an instance of {@link ReturnURLsType }
     * 
     */
    public ReturnURLsType createReturnURLsType() {
        return new ReturnURLsType();
    }

    /**
     * Create an instance of {@link MiscItemType }
     * 
     */
    public MiscItemType createMiscItemType() {
        return new MiscItemType();
    }

    /**
     * Create an instance of {@link DCCType }
     * 
     */
    public DCCType createDCCType() {
        return new DCCType();
    }

    /**
     * Create an instance of {@link SubBalanceType }
     * 
     */
    public SubBalanceType createSubBalanceType() {
        return new SubBalanceType();
    }

    /**
     * Create an instance of {@link IssuerNameType }
     * 
     */
    public IssuerNameType createIssuerNameType() {
        return new IssuerNameType();
    }

    /**
     * Create an instance of {@link RailType }
     * 
     */
    public RailType createRailType() {
        return new RailType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link SupplierMessagesType }
     * 
     */
    public SupplierMessagesType createSupplierMessagesType() {
        return new SupplierMessagesType();
    }

    /**
     * Create an instance of {@link AVSResultType }
     * 
     */
    public AVSResultType createAVSResultType() {
        return new AVSResultType();
    }

    /**
     * Create an instance of {@link VoucherType }
     * 
     */
    public VoucherType createVoucherType() {
        return new VoucherType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link HotelType }
     * 
     */
    public HotelType createHotelType() {
        return new HotelType();
    }

    /**
     * Create an instance of {@link ProductDetailType }
     * 
     */
    public ProductDetailType createProductDetailType() {
        return new ProductDetailType();
    }

    /**
     * Create an instance of {@link ProviderInfoType }
     * 
     */
    public ProviderInfoType createProviderInfoType() {
        return new ProviderInfoType();
    }

    /**
     * Create an instance of {@link CostType }
     * 
     */
    public CostType createCostType() {
        return new CostType();
    }

    /**
     * Create an instance of {@link FOPType }
     * 
     */
    public FOPType createFOPType() {
        return new FOPType();
    }

    /**
     * Create an instance of {@link PaymentInfoType }
     * 
     */
    public PaymentInfoType createPaymentInfoType() {
        return new PaymentInfoType();
    }

    /**
     * Create an instance of {@link FareBreakType }
     * 
     */
    public FareBreakType createFareBreakType() {
        return new FareBreakType();
    }

    /**
     * Create an instance of {@link CountryNameType }
     * 
     */
    public CountryNameType createCountryNameType() {
        return new CountryNameType();
    }

    /**
     * Create an instance of {@link RoomStayType }
     * 
     */
    public RoomStayType createRoomStayType() {
        return new RoomStayType();
    }

    /**
     * Create an instance of {@link TokensType.Token }
     * 
     */
    public TokensType.Token createTokensTypeToken() {
        return new TokensType.Token();
    }

    /**
     * Create an instance of {@link CarRentalType.Pickup }
     * 
     */
    public CarRentalType.Pickup createCarRentalTypePickup() {
        return new CarRentalType.Pickup();
    }

    /**
     * Create an instance of {@link CarRentalType.Return }
     * 
     */
    public CarRentalType.Return createCarRentalTypeReturn() {
        return new CarRentalType.Return();
    }

    /**
     * Create an instance of {@link CarRentalType.Renter }
     * 
     */
    public CarRentalType.Renter createCarRentalTypeRenter() {
        return new CarRentalType.Renter();
    }

    /**
     * Create an instance of {@link AddressType.StateProv }
     * 
     */
    public AddressType.StateProv createAddressTypeStateProv() {
        return new AddressType.StateProv();
    }

    /**
     * Create an instance of {@link DocumentType.EMDCouponDetail }
     * 
     */
    public DocumentType.EMDCouponDetail createDocumentTypeEMDCouponDetail() {
        return new DocumentType.EMDCouponDetail();
    }

    /**
     * Create an instance of {@link PersonIDType.Passport }
     * 
     */
    public PersonIDType.Passport createPersonIDTypePassport() {
        return new PersonIDType.Passport();
    }

    /**
     * Create an instance of {@link PersonIDType.Visa }
     * 
     */
    public PersonIDType.Visa createPersonIDTypeVisa() {
        return new PersonIDType.Visa();
    }

    /**
     * Create an instance of {@link PersonIDType.Other }
     * 
     */
    public PersonIDType.Other createPersonIDTypeOther() {
        return new PersonIDType.Other();
    }

    /**
     * Create an instance of {@link PassengerDetailType.Document }
     * 
     */
    public PassengerDetailType.Document createPassengerDetailTypeDocument() {
        return new PassengerDetailType.Document();
    }

    /**
     * Create an instance of {@link FlightDetailType.DepartureInfo }
     * 
     */
    public FlightDetailType.DepartureInfo createFlightDetailTypeDepartureInfo() {
        return new FlightDetailType.DepartureInfo();
    }

    /**
     * Create an instance of {@link FlightDetailType.ArrivalInfo }
     * 
     */
    public FlightDetailType.ArrivalInfo createFlightDetailTypeArrivalInfo() {
        return new FlightDetailType.ArrivalInfo();
    }

    /**
     * Create an instance of {@link PaymentCardType.T3DS }
     * 
     */
    public PaymentCardType.T3DS createPaymentCardTypeT3DS() {
        return new PaymentCardType.T3DS();
    }

    /**
     * Create an instance of {@link PaymentCardType.CardReader }
     * 
     */
    public PaymentCardType.CardReader createPaymentCardTypeCardReader() {
        return new PaymentCardType.CardReader();
    }

    /**
     * Create an instance of {@link PaymentCardType.CardHolderName }
     * 
     */
    public PaymentCardType.CardHolderName createPaymentCardTypeCardHolderName() {
        return new PaymentCardType.CardHolderName();
    }

    /**
     * Create an instance of {@link PaymentCardType.CardIssuerName }
     * 
     */
    public PaymentCardType.CardIssuerName createPaymentCardTypeCardIssuerName() {
        return new PaymentCardType.CardIssuerName();
    }

    /**
     * Create an instance of {@link PaymentCardType.VCLInfo }
     * 
     */
    public PaymentCardType.VCLInfo createPaymentCardTypeVCLInfo() {
        return new PaymentCardType.VCLInfo();
    }

    /**
     * Create an instance of {@link RailJourneyType.Ticket }
     * 
     */
    public RailJourneyType.Ticket createRailJourneyTypeTicket() {
        return new RailJourneyType.Ticket();
    }

    /**
     * Create an instance of {@link PaymentRS.NotificationList.Notification }
     * 
     */
    public PaymentRS.NotificationList.Notification createPaymentRSNotificationListNotification() {
        return new PaymentRS.NotificationList.Notification();
    }

    /**
     * Create an instance of {@link PaymentRS.AccountDetail.ListOfVouchers }
     * 
     */
    public PaymentRS.AccountDetail.ListOfVouchers createPaymentRSAccountDetailListOfVouchers() {
        return new PaymentRS.AccountDetail.ListOfVouchers();
    }

    /**
     * Create an instance of {@link AuthorizationResultType.CardReaderResult }
     * 
     */
    public AuthorizationResultType.CardReaderResult createAuthorizationResultTypeCardReaderResult() {
        return new AuthorizationResultType.CardReaderResult();
    }

    /**
     * Create an instance of {@link AuthorizationResultType.T3DSResult }
     * 
     */
    public AuthorizationResultType.T3DSResult createAuthorizationResultTypeT3DSResult() {
        return new AuthorizationResultType.T3DSResult();
    }

    /**
     * Create an instance of {@link AuthorizationResultType.PINResult }
     * 
     */
    public AuthorizationResultType.PINResult createAuthorizationResultTypePINResult() {
        return new AuthorizationResultType.PINResult();
    }

    /**
     * Create an instance of {@link AuthorizationResultType.AuthResponseDetail }
     * 
     */
    public AuthorizationResultType.AuthResponseDetail createAuthorizationResultTypeAuthResponseDetail() {
        return new AuthorizationResultType.AuthResponseDetail();
    }

    /**
     * Create an instance of {@link AuthorizationResultType.LocalCardDetail }
     * 
     */
    public AuthorizationResultType.LocalCardDetail createAuthorizationResultTypeLocalCardDetail() {
        return new AuthorizationResultType.LocalCardDetail();
    }

    /**
     * Create an instance of {@link PaymentRS.Results.AccountValidationResult }
     * 
     */
    public PaymentRS.Results.AccountValidationResult createPaymentRSResultsAccountValidationResult() {
        return new PaymentRS.Results.AccountValidationResult();
    }

    /**
     * Create an instance of {@link PaymentRS.Results.Remarks }
     * 
     */
    public PaymentRS.Results.Remarks createPaymentRSResultsRemarks() {
        return new PaymentRS.Results.Remarks();
    }

    /**
     * Create an instance of {@link PaymentDetailType.PaymentCard }
     * 
     */
    public PaymentDetailType.PaymentCard createPaymentDetailTypePaymentCard() {
        return new PaymentDetailType.PaymentCard();
    }

    /**
     * Create an instance of {@link PaymentDetailType.AmountDetail }
     * 
     */
    public PaymentDetailType.AmountDetail createPaymentDetailTypeAmountDetail() {
        return new PaymentDetailType.AmountDetail();
    }

    /**
     * Create an instance of {@link PaymentDetailType.AuthorizationResult }
     * 
     */
    public PaymentDetailType.AuthorizationResult createPaymentDetailTypeAuthorizationResult() {
        return new PaymentDetailType.AuthorizationResult();
    }

    /**
     * Create an instance of {@link PaymentDetailType.CardUsageResult }
     * 
     */
    public PaymentDetailType.CardUsageResult createPaymentDetailTypeCardUsageResult() {
        return new PaymentDetailType.CardUsageResult();
    }

    /**
     * Create an instance of {@link PaymentDetailType.RoutingDetail }
     * 
     */
    public PaymentDetailType.RoutingDetail createPaymentDetailTypeRoutingDetail() {
        return new PaymentDetailType.RoutingDetail();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail.HttpHeaders.HttpHeader }
     * 
     */
    public POSType.BrowserDetail.HttpHeaders.HttpHeader createPOSTypeBrowserDetailHttpHeadersHttpHeader() {
        return new POSType.BrowserDetail.HttpHeaders.HttpHeader();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPAExtensionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opentravel.org/OTA/2003/05/beta", name = "TPA_Extensions")
    public JAXBElement<TPAExtensionsType> createTPAExtensions(TPAExtensionsType value) {
        return new JAXBElement<TPAExtensionsType>(_TPAExtensions_QNAME, TPAExtensionsType.class, null, value);
    }

}
