//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Identification about a specific credit card
 * 
 * <p>Java class for PaymentCardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentCardType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DCC" type="{http://www.opentravel.org/OTA/2003/05/beta}DCCType" minOccurs="0"/>
 *         &lt;element name="T3DS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CAVV" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CAVV_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ECI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="XID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CaseNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PA_Response" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="VerificationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AuthenticationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MachineCookie" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CardReader" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}TokensType">
 *                 &lt;attribute name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ChipCardInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CardHolderName" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CardIssuerName" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}IssuerNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Address" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="PhoneNumber" type="{http://www.opentravel.org/OTA/2003/05/beta}PhoneType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Authenticated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CustomerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VCL_Info" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="MCC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CAI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplePayCryptogram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CardType" type="{http://www.opentravel.org/OTA/2003/05/beta}OTA_CodeType" />
 *       &lt;attribute name="CardCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssueNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PIN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CardSecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="T3DS_Ind" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MaskedCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TokenizedCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExtendPayment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Track1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Track2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReturnTokenInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentCardType", propOrder = {
    "dcc",
    "t3DS",
    "cardReader",
    "cardHolderName",
    "cardIssuerName",
    "address",
    "emailAddress",
    "phoneNumber",
    "dob",
    "ssn",
    "authenticated",
    "customerType",
    "vclInfo",
    "applePayCryptogram"
})
@XmlSeeAlso({
    com.sabre.hospitality.domain.payments.v300.PaymentDetailType.PaymentCard.class
})
public class PaymentCardType {

    @XmlElement(name = "DCC")
    protected DCCType dcc;
    @XmlElement(name = "T3DS")
    protected PaymentCardType.T3DS t3DS;
    @XmlElement(name = "CardReader")
    protected PaymentCardType.CardReader cardReader;
    @XmlElement(name = "CardHolderName")
    protected PaymentCardType.CardHolderName cardHolderName;
    @XmlElement(name = "CardIssuerName")
    protected PaymentCardType.CardIssuerName cardIssuerName;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "EmailAddress")
    protected List<String> emailAddress;
    @XmlElement(name = "PhoneNumber")
    protected List<PhoneType> phoneNumber;
    @XmlElement(name = "DOB")
    protected String dob;
    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "Authenticated")
    protected Boolean authenticated;
    @XmlElement(name = "CustomerType")
    protected String customerType;
    @XmlElement(name = "VCL_Info")
    protected PaymentCardType.VCLInfo vclInfo;
    @XmlElement(name = "ApplePayCryptogram")
    protected String applePayCryptogram;
    @XmlAttribute(name = "CardType")
    protected String cardType;
    @XmlAttribute(name = "CardCode")
    protected String cardCode;
    @XmlAttribute(name = "CardNumber")
    protected String cardNumber;
    @XmlAttribute(name = "IssueNumber")
    protected String issueNumber;
    @XmlAttribute(name = "PIN")
    protected String pin;
    @XmlAttribute(name = "CardSecurityCode")
    protected String cardSecurityCode;
    @XmlAttribute(name = "T3DS_Ind")
    protected Boolean t3DSInd;
    @XmlAttribute(name = "EffectiveDate")
    protected String effectiveDate;
    @XmlAttribute(name = "ExpireDate")
    protected String expireDate;
    @XmlAttribute(name = "MaskedCardNumber")
    protected String maskedCardNumber;
    @XmlAttribute(name = "TokenizedCardNumber")
    protected String tokenizedCardNumber;
    @XmlAttribute(name = "ExtendPayment")
    protected String extendPayment;
    @XmlAttribute(name = "Track1")
    protected String track1;
    @XmlAttribute(name = "Track2")
    protected String track2;
    @XmlAttribute(name = "ReturnTokenInd")
    protected Boolean returnTokenInd;

    /**
     * Gets the value of the dcc property.
     * 
     * @return
     *     possible object is
     *     {@link DCCType }
     *     
     */
    public DCCType getDCC() {
        return dcc;
    }

    /**
     * Sets the value of the dcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCCType }
     *     
     */
    public void setDCC(DCCType value) {
        this.dcc = value;
    }

    /**
     * Gets the value of the t3DS property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.T3DS }
     *     
     */
    public PaymentCardType.T3DS getT3DS() {
        return t3DS;
    }

    /**
     * Sets the value of the t3DS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.T3DS }
     *     
     */
    public void setT3DS(PaymentCardType.T3DS value) {
        this.t3DS = value;
    }

    /**
     * Gets the value of the cardReader property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.CardReader }
     *     
     */
    public PaymentCardType.CardReader getCardReader() {
        return cardReader;
    }

    /**
     * Sets the value of the cardReader property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.CardReader }
     *     
     */
    public void setCardReader(PaymentCardType.CardReader value) {
        this.cardReader = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.CardHolderName }
     *     
     */
    public PaymentCardType.CardHolderName getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.CardHolderName }
     *     
     */
    public void setCardHolderName(PaymentCardType.CardHolderName value) {
        this.cardHolderName = value;
    }

    /**
     * Gets the value of the cardIssuerName property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.CardIssuerName }
     *     
     */
    public PaymentCardType.CardIssuerName getCardIssuerName() {
        return cardIssuerName;
    }

    /**
     * Sets the value of the cardIssuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.CardIssuerName }
     *     
     */
    public void setCardIssuerName(PaymentCardType.CardIssuerName value) {
        this.cardIssuerName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEmailAddress() {
        if (emailAddress == null) {
            emailAddress = new ArrayList<String>();
        }
        return this.emailAddress;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneType }
     * 
     * 
     */
    public List<PhoneType> getPhoneNumber() {
        if (phoneNumber == null) {
            phoneNumber = new ArrayList<PhoneType>();
        }
        return this.phoneNumber;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the authenticated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuthenticated() {
        return authenticated;
    }

    /**
     * Sets the value of the authenticated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthenticated(Boolean value) {
        this.authenticated = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the vclInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.VCLInfo }
     *     
     */
    public PaymentCardType.VCLInfo getVCLInfo() {
        return vclInfo;
    }

    /**
     * Sets the value of the vclInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.VCLInfo }
     *     
     */
    public void setVCLInfo(PaymentCardType.VCLInfo value) {
        this.vclInfo = value;
    }

    /**
     * Gets the value of the applePayCryptogram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplePayCryptogram() {
        return applePayCryptogram;
    }

    /**
     * Sets the value of the applePayCryptogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplePayCryptogram(String value) {
        this.applePayCryptogram = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the cardCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * Sets the value of the cardCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCode(String value) {
        this.cardCode = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIN() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIN(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the cardSecurityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSecurityCode() {
        return cardSecurityCode;
    }

    /**
     * Sets the value of the cardSecurityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSecurityCode(String value) {
        this.cardSecurityCode = value;
    }

    /**
     * Gets the value of the t3DSInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isT3DSInd() {
        return t3DSInd;
    }

    /**
     * Sets the value of the t3DSInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setT3DSInd(Boolean value) {
        this.t3DSInd = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the maskedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskedCardNumber() {
        return maskedCardNumber;
    }

    /**
     * Sets the value of the maskedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskedCardNumber(String value) {
        this.maskedCardNumber = value;
    }

    /**
     * Gets the value of the tokenizedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenizedCardNumber() {
        return tokenizedCardNumber;
    }

    /**
     * Sets the value of the tokenizedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenizedCardNumber(String value) {
        this.tokenizedCardNumber = value;
    }

    /**
     * Gets the value of the extendPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendPayment() {
        return extendPayment;
    }

    /**
     * Sets the value of the extendPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendPayment(String value) {
        this.extendPayment = value;
    }

    /**
     * Gets the value of the track1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack1() {
        return track1;
    }

    /**
     * Sets the value of the track1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack1(String value) {
        this.track1 = value;
    }

    /**
     * Gets the value of the track2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack2() {
        return track2;
    }

    /**
     * Sets the value of the track2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack2(String value) {
        this.track2 = value;
    }

    /**
     * Gets the value of the returnTokenInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnTokenInd() {
        return returnTokenInd;
    }

    /**
     * Sets the value of the returnTokenInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnTokenInd(Boolean value) {
        this.returnTokenInd = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CardHolderName {

        @XmlAttribute(name = "Name")
        protected String name;
        @XmlAttribute(name = "FirstName")
        protected String firstName;
        @XmlAttribute(name = "LastName")
        protected String lastName;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}IssuerNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CardIssuerName {

        @XmlAttribute(name = "BankName")
        protected String bankName;
        @XmlAttribute(name = "BankID")
        protected String bankID;

        /**
         * Gets the value of the bankName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankName() {
            return bankName;
        }

        /**
         * Sets the value of the bankName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankName(String value) {
            this.bankName = value;
        }

        /**
         * Gets the value of the bankID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankID() {
            return bankID;
        }

        /**
         * Sets the value of the bankID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankID(String value) {
            this.bankID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}TokensType">
     *       &lt;attribute name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ChipCardInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CardReader
        extends TokensType
    {

        @XmlAttribute(name = "DeviceType")
        protected String deviceType;
        @XmlAttribute(name = "DeviceID")
        protected String deviceID;
        @XmlAttribute(name = "ChipCardInd")
        protected Boolean chipCardInd;

        /**
         * Gets the value of the deviceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceType() {
            return deviceType;
        }

        /**
         * Sets the value of the deviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceType(String value) {
            this.deviceType = value;
        }

        /**
         * Gets the value of the deviceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceID() {
            return deviceID;
        }

        /**
         * Sets the value of the deviceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceID(String value) {
            this.deviceID = value;
        }

        /**
         * Gets the value of the chipCardInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isChipCardInd() {
            return chipCardInd;
        }

        /**
         * Sets the value of the chipCardInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setChipCardInd(Boolean value) {
            this.chipCardInd = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CAVV" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CAVV_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ECI" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="XID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CaseNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PA_Response" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="VerificationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AuthenticationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MachineCookie" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class T3DS {

        @XmlAttribute(name = "CAVV")
        protected String cavv;
        @XmlAttribute(name = "CAVV_Algorithm")
        protected String cavvAlgorithm;
        @XmlAttribute(name = "ECI")
        protected String eci;
        @XmlAttribute(name = "XID")
        protected String xid;
        @XmlAttribute(name = "CaseNumber")
        protected Integer caseNumber;
        @XmlAttribute(name = "MD")
        protected String md;
        @XmlAttribute(name = "PA_Response")
        protected String paResponse;
        @XmlAttribute(name = "VerificationResult")
        protected String verificationResult;
        @XmlAttribute(name = "AuthenticationResult")
        protected String authenticationResult;
        @XmlAttribute(name = "MachineCookie")
        protected String machineCookie;

        /**
         * Gets the value of the cavv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVV() {
            return cavv;
        }

        /**
         * Sets the value of the cavv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVV(String value) {
            this.cavv = value;
        }

        /**
         * Gets the value of the cavvAlgorithm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVVAlgorithm() {
            return cavvAlgorithm;
        }

        /**
         * Sets the value of the cavvAlgorithm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVVAlgorithm(String value) {
            this.cavvAlgorithm = value;
        }

        /**
         * Gets the value of the eci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getECI() {
            return eci;
        }

        /**
         * Sets the value of the eci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setECI(String value) {
            this.eci = value;
        }

        /**
         * Gets the value of the xid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXID() {
            return xid;
        }

        /**
         * Sets the value of the xid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXID(String value) {
            this.xid = value;
        }

        /**
         * Gets the value of the caseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCaseNumber() {
            return caseNumber;
        }

        /**
         * Sets the value of the caseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCaseNumber(Integer value) {
            this.caseNumber = value;
        }

        /**
         * Gets the value of the md property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMD() {
            return md;
        }

        /**
         * Sets the value of the md property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMD(String value) {
            this.md = value;
        }

        /**
         * Gets the value of the paResponse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPAResponse() {
            return paResponse;
        }

        /**
         * Sets the value of the paResponse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPAResponse(String value) {
            this.paResponse = value;
        }

        /**
         * Gets the value of the verificationResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerificationResult() {
            return verificationResult;
        }

        /**
         * Sets the value of the verificationResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerificationResult(String value) {
            this.verificationResult = value;
        }

        /**
         * Gets the value of the authenticationResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthenticationResult() {
            return authenticationResult;
        }

        /**
         * Sets the value of the authenticationResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthenticationResult(String value) {
            this.authenticationResult = value;
        }

        /**
         * Gets the value of the machineCookie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMachineCookie() {
            return machineCookie;
        }

        /**
         * Sets the value of the machineCookie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMachineCookie(String value) {
            this.machineCookie = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="MCC" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CAI" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VCLInfo {

        @XmlAttribute(name = "MCC")
        protected String mcc;
        @XmlAttribute(name = "AID")
        protected String aid;
        @XmlAttribute(name = "CAI")
        protected String cai;

        /**
         * Gets the value of the mcc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMCC() {
            return mcc;
        }

        /**
         * Sets the value of the mcc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMCC(String value) {
            this.mcc = value;
        }

        /**
         * Gets the value of the aid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAID() {
            return aid;
        }

        /**
         * Sets the value of the aid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAID(String value) {
            this.aid = value;
        }

        /**
         * Gets the value of the cai property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAI() {
            return cai;
        }

        /**
         * Sets the value of the cai property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAI(String value) {
            this.cai = value;
        }

    }

}
