//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="POS" type="{http://www.opentravel.org/OTA/2003/05/beta}POS_Type"/>
 *         &lt;element name="ServiceIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="MultiFOPsProcessInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FraudScreenInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MerchantDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}MerchantDetailType"/>
 *         &lt;element name="OrderDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProductDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}ProductDetailType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="PassengerDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="ContactInfo" type="{http://www.opentravel.org/OTA/2003/05/beta}ContactInfoType" minOccurs="0"/>
 *                   &lt;element name="FlightDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}FlightDetailType" maxOccurs="20" minOccurs="0"/>
 *                   &lt;element name="Hotel" type="{http://www.opentravel.org/OTA/2003/05/beta}HotelType" maxOccurs="5" minOccurs="0"/>
 *                   &lt;element name="CarRental" type="{http://www.opentravel.org/OTA/2003/05/beta}CarRentalType" maxOccurs="5" minOccurs="0"/>
 *                   &lt;element name="Rail" type="{http://www.opentravel.org/OTA/2003/05/beta}RailType" maxOccurs="5" minOccurs="0"/>
 *                   &lt;element name="ShippingAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType" minOccurs="0"/>
 *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="UniqueBookingID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SessionID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RecordLocator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DollarAmountPaid" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *                 &lt;attribute name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ThirdPartyBookingInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="OneWayInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="MultiCityInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="PromotionCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ValidatingCarrierCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ValidatingCarrierNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}AccountDetailType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="PaymentDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}PaymentDetailType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="CustomerDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Address" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType" minOccurs="0"/>
 *                   &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PhoneNumber" type="{http://www.opentravel.org/OTA/2003/05/beta}PhoneType" maxOccurs="3" minOccurs="0"/>
 *                   &lt;element name="CustomerID" type="{http://www.opentravel.org/OTA/2003/05/beta}PersonID_Type" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
 *                 &lt;attribute name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SystemDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="SabreTransactionID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DeferredPaymentID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ReturnSupplierMessagesInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="RetransmissionIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action",
    "pos",
    "serviceIndicator",
    "merchantDetail",
    "orderDetail",
    "accountDetail",
    "paymentDetail",
    "customerDetail"
})
@XmlRootElement(name = "PaymentRQ")
public class PaymentRQ {

    @XmlElement(name = "Action", required = true)
    protected PaymentRQ.Action action;
    @XmlElement(name = "POS", required = true)
    protected POSType pos;
    @XmlElement(name = "ServiceIndicator")
    protected PaymentRQ.ServiceIndicator serviceIndicator;
    @XmlElement(name = "MerchantDetail", required = true)
    protected MerchantDetailType merchantDetail;
    @XmlElement(name = "OrderDetail")
    protected PaymentRQ.OrderDetail orderDetail;
    @XmlElement(name = "AccountDetail")
    protected List<AccountDetailType> accountDetail;
    @XmlElement(name = "PaymentDetail")
    protected List<PaymentDetailType> paymentDetail;
    @XmlElement(name = "CustomerDetail")
    protected PaymentRQ.CustomerDetail customerDetail;
    @XmlAttribute(name = "SystemDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar systemDateTime;
    @XmlAttribute(name = "SabreTransactionID")
    protected String sabreTransactionID;
    @XmlAttribute(name = "DeferredPaymentID")
    @XmlSchemaType(name = "anySimpleType")
    protected String deferredPaymentID;
    @XmlAttribute(name = "ReturnSupplierMessagesInd")
    protected Boolean returnSupplierMessagesInd;
    @XmlAttribute(name = "RetransmissionIndicator")
    protected Boolean retransmissionIndicator;
    @XmlAttribute(name = "Version", required = true)
    protected String version;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRQ.Action }
     *     
     */
    public PaymentRQ.Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRQ.Action }
     *     
     */
    public void setAction(PaymentRQ.Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POSType }
     *     
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSType }
     *     
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the serviceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRQ.ServiceIndicator }
     *     
     */
    public PaymentRQ.ServiceIndicator getServiceIndicator() {
        return serviceIndicator;
    }

    /**
     * Sets the value of the serviceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRQ.ServiceIndicator }
     *     
     */
    public void setServiceIndicator(PaymentRQ.ServiceIndicator value) {
        this.serviceIndicator = value;
    }

    /**
     * Gets the value of the merchantDetail property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantDetailType }
     *     
     */
    public MerchantDetailType getMerchantDetail() {
        return merchantDetail;
    }

    /**
     * Sets the value of the merchantDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantDetailType }
     *     
     */
    public void setMerchantDetail(MerchantDetailType value) {
        this.merchantDetail = value;
    }

    /**
     * Gets the value of the orderDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRQ.OrderDetail }
     *     
     */
    public PaymentRQ.OrderDetail getOrderDetail() {
        return orderDetail;
    }

    /**
     * Sets the value of the orderDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRQ.OrderDetail }
     *     
     */
    public void setOrderDetail(PaymentRQ.OrderDetail value) {
        this.orderDetail = value;
    }

    /**
     * Gets the value of the accountDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountDetailType }
     * 
     * 
     */
    public List<AccountDetailType> getAccountDetail() {
        if (accountDetail == null) {
            accountDetail = new ArrayList<AccountDetailType>();
        }
        return this.accountDetail;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentDetailType }
     * 
     * 
     */
    public List<PaymentDetailType> getPaymentDetail() {
        if (paymentDetail == null) {
            paymentDetail = new ArrayList<PaymentDetailType>();
        }
        return this.paymentDetail;
    }

    /**
     * Gets the value of the customerDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRQ.CustomerDetail }
     *     
     */
    public PaymentRQ.CustomerDetail getCustomerDetail() {
        return customerDetail;
    }

    /**
     * Sets the value of the customerDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRQ.CustomerDetail }
     *     
     */
    public void setCustomerDetail(PaymentRQ.CustomerDetail value) {
        this.customerDetail = value;
    }

    /**
     * Gets the value of the systemDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSystemDateTime() {
        return systemDateTime;
    }

    /**
     * Sets the value of the systemDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSystemDateTime(XMLGregorianCalendar value) {
        this.systemDateTime = value;
    }

    /**
     * Gets the value of the sabreTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSabreTransactionID() {
        return sabreTransactionID;
    }

    /**
     * Sets the value of the sabreTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSabreTransactionID(String value) {
        this.sabreTransactionID = value;
    }

    /**
     * Gets the value of the deferredPaymentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferredPaymentID() {
        return deferredPaymentID;
    }

    /**
     * Sets the value of the deferredPaymentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferredPaymentID(String value) {
        this.deferredPaymentID = value;
    }

    /**
     * Gets the value of the returnSupplierMessagesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnSupplierMessagesInd() {
        return returnSupplierMessagesInd;
    }

    /**
     * Sets the value of the returnSupplierMessagesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnSupplierMessagesInd(Boolean value) {
        this.returnSupplierMessagesInd = value;
    }

    /**
     * Gets the value of the retransmissionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetransmissionIndicator() {
        return retransmissionIndicator;
    }

    /**
     * Sets the value of the retransmissionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetransmissionIndicator(Boolean value) {
        this.retransmissionIndicator = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Action {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Type")
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Address" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType" minOccurs="0"/>
     *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PhoneNumber" type="{http://www.opentravel.org/OTA/2003/05/beta}PhoneType" maxOccurs="3" minOccurs="0"/>
     *         &lt;element name="CustomerID" type="{http://www.opentravel.org/OTA/2003/05/beta}PersonID_Type" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}PersonNameGroup"/>
     *       &lt;attribute name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address",
        "emailAddress",
        "phoneNumber",
        "customerID"
    })
    public static class CustomerDetail {

        @XmlElement(name = "Address")
        protected AddressType address;
        @XmlElement(name = "EmailAddress")
        protected String emailAddress;
        @XmlElement(name = "PhoneNumber")
        protected List<PhoneType> phoneNumber;
        @XmlElement(name = "CustomerID")
        protected PersonIDType customerID;
        @XmlAttribute(name = "DOB")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dob;
        @XmlAttribute(name = "Gender")
        protected String gender;
        @XmlAttribute(name = "Type")
        protected String type;
        @XmlAttribute(name = "Name")
        protected String name;
        @XmlAttribute(name = "FirstName")
        protected String firstName;
        @XmlAttribute(name = "LastName")
        protected String lastName;

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setAddress(AddressType value) {
            this.address = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoneNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PhoneType }
         * 
         * 
         */
        public List<PhoneType> getPhoneNumber() {
            if (phoneNumber == null) {
                phoneNumber = new ArrayList<PhoneType>();
            }
            return this.phoneNumber;
        }

        /**
         * Gets the value of the customerID property.
         * 
         * @return
         *     possible object is
         *     {@link PersonIDType }
         *     
         */
        public PersonIDType getCustomerID() {
            return customerID;
        }

        /**
         * Sets the value of the customerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonIDType }
         *     
         */
        public void setCustomerID(PersonIDType value) {
            this.customerID = value;
        }

        /**
         * Gets the value of the dob property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDOB() {
            return dob;
        }

        /**
         * Sets the value of the dob property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDOB(XMLGregorianCalendar value) {
            this.dob = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProductDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}ProductDetailType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="PassengerDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="ContactInfo" type="{http://www.opentravel.org/OTA/2003/05/beta}ContactInfoType" minOccurs="0"/>
     *         &lt;element name="FlightDetail" type="{http://www.opentravel.org/OTA/2003/05/beta}FlightDetailType" maxOccurs="20" minOccurs="0"/>
     *         &lt;element name="Hotel" type="{http://www.opentravel.org/OTA/2003/05/beta}HotelType" maxOccurs="5" minOccurs="0"/>
     *         &lt;element name="CarRental" type="{http://www.opentravel.org/OTA/2003/05/beta}CarRentalType" maxOccurs="5" minOccurs="0"/>
     *         &lt;element name="Rail" type="{http://www.opentravel.org/OTA/2003/05/beta}RailType" maxOccurs="5" minOccurs="0"/>
     *         &lt;element name="ShippingAddress" type="{http://www.opentravel.org/OTA/2003/05/beta}AddressType" minOccurs="0"/>
     *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="UniqueBookingID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SessionID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RecordLocator" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DollarAmountPaid" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
     *       &lt;attribute name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ThirdPartyBookingInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="OneWayInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="MultiCityInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="PromotionCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ValidatingCarrierCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ValidatingCarrierNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productDetail",
        "passengerDetail",
        "contactInfo",
        "flightDetail",
        "hotel",
        "carRental",
        "rail",
        "shippingAddress",
        "remarks"
    })
    public static class OrderDetail {

        @XmlElement(name = "ProductDetail")
        protected List<ProductDetailType> productDetail;
        @XmlElement(name = "PassengerDetail")
        protected List<PassengerDetailType> passengerDetail;
        @XmlElement(name = "ContactInfo")
        protected ContactInfoType contactInfo;
        @XmlElement(name = "FlightDetail")
        protected List<FlightDetailType> flightDetail;
        @XmlElement(name = "Hotel")
        protected List<HotelType> hotel;
        @XmlElement(name = "CarRental")
        protected List<CarRentalType> carRental;
        @XmlElement(name = "Rail")
        protected List<RailType> rail;
        @XmlElement(name = "ShippingAddress")
        protected AddressType shippingAddress;
        @XmlElement(name = "Remarks")
        protected String remarks;
        @XmlAttribute(name = "UniqueBookingID")
        protected String uniqueBookingID;
        @XmlAttribute(name = "SessionID")
        protected String sessionID;
        @XmlAttribute(name = "OrderID")
        protected String orderID;
        @XmlAttribute(name = "OrderType")
        protected String orderType;
        @XmlAttribute(name = "RecordLocator")
        protected String recordLocator;
        @XmlAttribute(name = "DollarAmountPaid")
        protected BigDecimal dollarAmountPaid;
        @XmlAttribute(name = "InvoiceNumber")
        protected String invoiceNumber;
        @XmlAttribute(name = "ThirdPartyBookingInd")
        protected Boolean thirdPartyBookingInd;
        @XmlAttribute(name = "OneWayInd")
        protected Boolean oneWayInd;
        @XmlAttribute(name = "MultiCityInd")
        protected Boolean multiCityInd;
        @XmlAttribute(name = "PromotionCode")
        protected String promotionCode;
        @XmlAttribute(name = "ValidatingCarrierCode")
        protected String validatingCarrierCode;
        @XmlAttribute(name = "ValidatingCarrierNbr")
        protected String validatingCarrierNbr;

        /**
         * Gets the value of the productDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProductDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProductDetailType }
         * 
         * 
         */
        public List<ProductDetailType> getProductDetail() {
            if (productDetail == null) {
                productDetail = new ArrayList<ProductDetailType>();
            }
            return this.productDetail;
        }

        /**
         * Gets the value of the passengerDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassengerDetailType }
         * 
         * 
         */
        public List<PassengerDetailType> getPassengerDetail() {
            if (passengerDetail == null) {
                passengerDetail = new ArrayList<PassengerDetailType>();
            }
            return this.passengerDetail;
        }

        /**
         * Gets the value of the contactInfo property.
         * 
         * @return
         *     possible object is
         *     {@link ContactInfoType }
         *     
         */
        public ContactInfoType getContactInfo() {
            return contactInfo;
        }

        /**
         * Sets the value of the contactInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContactInfoType }
         *     
         */
        public void setContactInfo(ContactInfoType value) {
            this.contactInfo = value;
        }

        /**
         * Gets the value of the flightDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flightDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlightDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightDetailType }
         * 
         * 
         */
        public List<FlightDetailType> getFlightDetail() {
            if (flightDetail == null) {
                flightDetail = new ArrayList<FlightDetailType>();
            }
            return this.flightDetail;
        }

        /**
         * Gets the value of the hotel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hotel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelType }
         * 
         * 
         */
        public List<HotelType> getHotel() {
            if (hotel == null) {
                hotel = new ArrayList<HotelType>();
            }
            return this.hotel;
        }

        /**
         * Gets the value of the carRental property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the carRental property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCarRental().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CarRentalType }
         * 
         * 
         */
        public List<CarRentalType> getCarRental() {
            if (carRental == null) {
                carRental = new ArrayList<CarRentalType>();
            }
            return this.carRental;
        }

        /**
         * Gets the value of the rail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RailType }
         * 
         * 
         */
        public List<RailType> getRail() {
            if (rail == null) {
                rail = new ArrayList<RailType>();
            }
            return this.rail;
        }

        /**
         * Gets the value of the shippingAddress property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getShippingAddress() {
            return shippingAddress;
        }

        /**
         * Sets the value of the shippingAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setShippingAddress(AddressType value) {
            this.shippingAddress = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

        /**
         * Gets the value of the uniqueBookingID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniqueBookingID() {
            return uniqueBookingID;
        }

        /**
         * Sets the value of the uniqueBookingID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniqueBookingID(String value) {
            this.uniqueBookingID = value;
        }

        /**
         * Gets the value of the sessionID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSessionID() {
            return sessionID;
        }

        /**
         * Sets the value of the sessionID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        /**
         * Gets the value of the orderID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderID() {
            return orderID;
        }

        /**
         * Sets the value of the orderID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderID(String value) {
            this.orderID = value;
        }

        /**
         * Gets the value of the orderType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderType() {
            return orderType;
        }

        /**
         * Sets the value of the orderType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderType(String value) {
            this.orderType = value;
        }

        /**
         * Gets the value of the recordLocator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordLocator() {
            return recordLocator;
        }

        /**
         * Sets the value of the recordLocator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordLocator(String value) {
            this.recordLocator = value;
        }

        /**
         * Gets the value of the dollarAmountPaid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDollarAmountPaid() {
            return dollarAmountPaid;
        }

        /**
         * Sets the value of the dollarAmountPaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDollarAmountPaid(BigDecimal value) {
            this.dollarAmountPaid = value;
        }

        /**
         * Gets the value of the invoiceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoiceNumber() {
            return invoiceNumber;
        }

        /**
         * Sets the value of the invoiceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoiceNumber(String value) {
            this.invoiceNumber = value;
        }

        /**
         * Gets the value of the thirdPartyBookingInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isThirdPartyBookingInd() {
            return thirdPartyBookingInd;
        }

        /**
         * Sets the value of the thirdPartyBookingInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setThirdPartyBookingInd(Boolean value) {
            this.thirdPartyBookingInd = value;
        }

        /**
         * Gets the value of the oneWayInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOneWayInd() {
            return oneWayInd;
        }

        /**
         * Sets the value of the oneWayInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOneWayInd(Boolean value) {
            this.oneWayInd = value;
        }

        /**
         * Gets the value of the multiCityInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMultiCityInd() {
            return multiCityInd;
        }

        /**
         * Sets the value of the multiCityInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMultiCityInd(Boolean value) {
            this.multiCityInd = value;
        }

        /**
         * Gets the value of the promotionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromotionCode() {
            return promotionCode;
        }

        /**
         * Sets the value of the promotionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromotionCode(String value) {
            this.promotionCode = value;
        }

        /**
         * Gets the value of the validatingCarrierCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidatingCarrierCode() {
            return validatingCarrierCode;
        }

        /**
         * Sets the value of the validatingCarrierCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidatingCarrierCode(String value) {
            this.validatingCarrierCode = value;
        }

        /**
         * Gets the value of the validatingCarrierNbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidatingCarrierNbr() {
            return validatingCarrierNbr;
        }

        /**
         * Sets the value of the validatingCarrierNbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidatingCarrierNbr(String value) {
            this.validatingCarrierNbr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="MultiFOPsProcessInd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="FraudScreenInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ServiceIndicator {

        @XmlAttribute(name = "MultiFOPsProcessInd")
        protected String multiFOPsProcessInd;
        @XmlAttribute(name = "FraudScreenInd")
        protected Boolean fraudScreenInd;

        /**
         * Gets the value of the multiFOPsProcessInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMultiFOPsProcessInd() {
            return multiFOPsProcessInd;
        }

        /**
         * Sets the value of the multiFOPsProcessInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMultiFOPsProcessInd(String value) {
            this.multiFOPsProcessInd = value;
        }

        /**
         * Gets the value of the fraudScreenInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFraudScreenInd() {
            return fraudScreenInd;
        }

        /**
         * Sets the value of the fraudScreenInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFraudScreenInd(Boolean value) {
            this.fraudScreenInd = value;
        }

    }

}
