//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="PaymentMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentSite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PurchaseSite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentTerm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PayDateLookupCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TermDateBasis" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentInfoType")
public class PaymentInfoType {

    @XmlAttribute(name = "PaymentMethod")
    protected String paymentMethod;
    @XmlAttribute(name = "PaymentSite")
    protected String paymentSite;
    @XmlAttribute(name = "PurchaseSite")
    protected String purchaseSite;
    @XmlAttribute(name = "PaymentTerm")
    protected String paymentTerm;
    @XmlAttribute(name = "PayDateLookupCode")
    protected String payDateLookupCode;
    @XmlAttribute(name = "TermDateBasis")
    protected String termDateBasis;

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the paymentSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentSite() {
        return paymentSite;
    }

    /**
     * Sets the value of the paymentSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentSite(String value) {
        this.paymentSite = value;
    }

    /**
     * Gets the value of the purchaseSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseSite() {
        return purchaseSite;
    }

    /**
     * Sets the value of the purchaseSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseSite(String value) {
        this.purchaseSite = value;
    }

    /**
     * Gets the value of the paymentTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerm() {
        return paymentTerm;
    }

    /**
     * Sets the value of the paymentTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerm(String value) {
        this.paymentTerm = value;
    }

    /**
     * Gets the value of the payDateLookupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayDateLookupCode() {
        return payDateLookupCode;
    }

    /**
     * Sets the value of the payDateLookupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayDateLookupCode(String value) {
        this.payDateLookupCode = value;
    }

    /**
     * Gets the value of the termDateBasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermDateBasis() {
        return termDateBasis;
    }

    /**
     * Sets the value of the termDateBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermDateBasis(String value) {
        this.termDateBasis = value;
    }

}
