//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FOP" type="{http://www.opentravel.org/OTA/2003/05/beta}FOPType" minOccurs="0"/>
 *         &lt;element name="PaymentCard" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}PaymentCardType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AmountDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}CurrencyAmountType">
 *                 &lt;attribute name="BonusAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *                 &lt;attribute name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="TicketingCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TicketingAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AuthorizationResult" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ApprovalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AVS_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CSC_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CAVV_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SupplierTransID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SupplierFOP_Code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SupplierResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MerchantAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CardUsageResult" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ReferenceNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CardDeploymentID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReturnURLs" type="{http://www.opentravel.org/OTA/2003/05/beta}ReturnURLsType" minOccurs="0"/>
 *         &lt;element name="RoutingDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}UserNameGroup"/>
 *                 &lt;attribute name="SupplierID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MerchantAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PSP_HostedID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SignatureKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="FOP_RPH" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PaymentRef" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DeferredPaymentPeriod" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentDetailType", propOrder = {
    "fop",
    "paymentCard",
    "amountDetail",
    "authorizationResult",
    "cardUsageResult",
    "returnURLs",
    "routingDetail"
})
public class PaymentDetailType {

    @XmlElement(name = "FOP")
    protected FOPType fop;
    @XmlElement(name = "PaymentCard")
    protected PaymentDetailType.PaymentCard paymentCard;
    @XmlElement(name = "AmountDetail")
    protected PaymentDetailType.AmountDetail amountDetail;
    @XmlElement(name = "AuthorizationResult")
    protected PaymentDetailType.AuthorizationResult authorizationResult;
    @XmlElement(name = "CardUsageResult")
    protected PaymentDetailType.CardUsageResult cardUsageResult;
    @XmlElement(name = "ReturnURLs")
    protected ReturnURLsType returnURLs;
    @XmlElement(name = "RoutingDetail")
    protected PaymentDetailType.RoutingDetail routingDetail;
    @XmlAttribute(name = "FOP_RPH")
    @XmlSchemaType(name = "anySimpleType")
    protected String foprph;
    @XmlAttribute(name = "PaymentRef")
    @XmlSchemaType(name = "anySimpleType")
    protected String paymentRef;
    @XmlAttribute(name = "DeferredPaymentPeriod")
    @XmlSchemaType(name = "anySimpleType")
    protected String deferredPaymentPeriod;

    /**
     * Gets the value of the fop property.
     * 
     * @return
     *     possible object is
     *     {@link FOPType }
     *     
     */
    public FOPType getFOP() {
        return fop;
    }

    /**
     * Sets the value of the fop property.
     * 
     * @param value
     *     allowed object is
     *     {@link FOPType }
     *     
     */
    public void setFOP(FOPType value) {
        this.fop = value;
    }

    /**
     * Gets the value of the paymentCard property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.PaymentCard }
     *     
     */
    public PaymentDetailType.PaymentCard getPaymentCard() {
        return paymentCard;
    }

    /**
     * Sets the value of the paymentCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.PaymentCard }
     *     
     */
    public void setPaymentCard(PaymentDetailType.PaymentCard value) {
        this.paymentCard = value;
    }

    /**
     * Gets the value of the amountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.AmountDetail }
     *     
     */
    public PaymentDetailType.AmountDetail getAmountDetail() {
        return amountDetail;
    }

    /**
     * Sets the value of the amountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.AmountDetail }
     *     
     */
    public void setAmountDetail(PaymentDetailType.AmountDetail value) {
        this.amountDetail = value;
    }

    /**
     * Gets the value of the authorizationResult property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.AuthorizationResult }
     *     
     */
    public PaymentDetailType.AuthorizationResult getAuthorizationResult() {
        return authorizationResult;
    }

    /**
     * Sets the value of the authorizationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.AuthorizationResult }
     *     
     */
    public void setAuthorizationResult(PaymentDetailType.AuthorizationResult value) {
        this.authorizationResult = value;
    }

    /**
     * Gets the value of the cardUsageResult property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.CardUsageResult }
     *     
     */
    public PaymentDetailType.CardUsageResult getCardUsageResult() {
        return cardUsageResult;
    }

    /**
     * Sets the value of the cardUsageResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.CardUsageResult }
     *     
     */
    public void setCardUsageResult(PaymentDetailType.CardUsageResult value) {
        this.cardUsageResult = value;
    }

    /**
     * Gets the value of the returnURLs property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnURLsType }
     *     
     */
    public ReturnURLsType getReturnURLs() {
        return returnURLs;
    }

    /**
     * Sets the value of the returnURLs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnURLsType }
     *     
     */
    public void setReturnURLs(ReturnURLsType value) {
        this.returnURLs = value;
    }

    /**
     * Gets the value of the routingDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.RoutingDetail }
     *     
     */
    public PaymentDetailType.RoutingDetail getRoutingDetail() {
        return routingDetail;
    }

    /**
     * Sets the value of the routingDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.RoutingDetail }
     *     
     */
    public void setRoutingDetail(PaymentDetailType.RoutingDetail value) {
        this.routingDetail = value;
    }

    /**
     * Gets the value of the foprph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOPRPH() {
        return foprph;
    }

    /**
     * Sets the value of the foprph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOPRPH(String value) {
        this.foprph = value;
    }

    /**
     * Gets the value of the paymentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRef() {
        return paymentRef;
    }

    /**
     * Sets the value of the paymentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRef(String value) {
        this.paymentRef = value;
    }

    /**
     * Gets the value of the deferredPaymentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferredPaymentPeriod() {
        return deferredPaymentPeriod;
    }

    /**
     * Sets the value of the deferredPaymentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferredPaymentPeriod(String value) {
        this.deferredPaymentPeriod = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}CurrencyAmountType">
     *       &lt;attribute name="BonusAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
     *       &lt;attribute name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="TicketingCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TicketingAmount" type="{http://www.opentravel.org/OTA/2003/05/beta}Money" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AmountDetail
        extends CurrencyAmountType
    {

        @XmlAttribute(name = "BonusAmount")
        protected BigDecimal bonusAmount;
        @XmlAttribute(name = "Points")
        protected BigInteger points;
        @XmlAttribute(name = "TicketingCurrencyCode")
        protected String ticketingCurrencyCode;
        @XmlAttribute(name = "TicketingAmount")
        protected BigDecimal ticketingAmount;

        /**
         * Gets the value of the bonusAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBonusAmount() {
            return bonusAmount;
        }

        /**
         * Sets the value of the bonusAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBonusAmount(BigDecimal value) {
            this.bonusAmount = value;
        }

        /**
         * Gets the value of the points property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPoints() {
            return points;
        }

        /**
         * Sets the value of the points property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPoints(BigInteger value) {
            this.points = value;
        }

        /**
         * Gets the value of the ticketingCurrencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTicketingCurrencyCode() {
            return ticketingCurrencyCode;
        }

        /**
         * Sets the value of the ticketingCurrencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTicketingCurrencyCode(String value) {
            this.ticketingCurrencyCode = value;
        }

        /**
         * Gets the value of the ticketingAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTicketingAmount() {
            return ticketingAmount;
        }

        /**
         * Sets the value of the ticketingAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTicketingAmount(BigDecimal value) {
            this.ticketingAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ApprovalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AVS_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CSC_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CAVV_ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SupplierTransID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SupplierFOP_Code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SupplierResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MerchantAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AuthorizationResult {

        @XmlAttribute(name = "ResponseCode")
        protected String responseCode;
        @XmlAttribute(name = "ApprovalCode")
        protected String approvalCode;
        @XmlAttribute(name = "AVS_ResultCode")
        protected String avsResultCode;
        @XmlAttribute(name = "CSC_ResultCode")
        protected String cscResultCode;
        @XmlAttribute(name = "CAVV_ResultCode")
        protected String cavvResultCode;
        @XmlAttribute(name = "SupplierID")
        protected String supplierID;
        @XmlAttribute(name = "SupplierTransID")
        protected String supplierTransID;
        @XmlAttribute(name = "SupplierFOP_Code")
        protected String supplierFOPCode;
        @XmlAttribute(name = "SupplierResponseCode")
        protected String supplierResponseCode;
        @XmlAttribute(name = "MerchantAccountNumber")
        protected String merchantAccountNumber;

        /**
         * Gets the value of the responseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseCode() {
            return responseCode;
        }

        /**
         * Sets the value of the responseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseCode(String value) {
            this.responseCode = value;
        }

        /**
         * Gets the value of the approvalCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalCode() {
            return approvalCode;
        }

        /**
         * Sets the value of the approvalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalCode(String value) {
            this.approvalCode = value;
        }

        /**
         * Gets the value of the avsResultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAVSResultCode() {
            return avsResultCode;
        }

        /**
         * Sets the value of the avsResultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAVSResultCode(String value) {
            this.avsResultCode = value;
        }

        /**
         * Gets the value of the cscResultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCSCResultCode() {
            return cscResultCode;
        }

        /**
         * Sets the value of the cscResultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCSCResultCode(String value) {
            this.cscResultCode = value;
        }

        /**
         * Gets the value of the cavvResultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVVResultCode() {
            return cavvResultCode;
        }

        /**
         * Sets the value of the cavvResultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVVResultCode(String value) {
            this.cavvResultCode = value;
        }

        /**
         * Gets the value of the supplierID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierID() {
            return supplierID;
        }

        /**
         * Sets the value of the supplierID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierID(String value) {
            this.supplierID = value;
        }

        /**
         * Gets the value of the supplierTransID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierTransID() {
            return supplierTransID;
        }

        /**
         * Sets the value of the supplierTransID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierTransID(String value) {
            this.supplierTransID = value;
        }

        /**
         * Gets the value of the supplierFOPCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierFOPCode() {
            return supplierFOPCode;
        }

        /**
         * Sets the value of the supplierFOPCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierFOPCode(String value) {
            this.supplierFOPCode = value;
        }

        /**
         * Gets the value of the supplierResponseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierResponseCode() {
            return supplierResponseCode;
        }

        /**
         * Sets the value of the supplierResponseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierResponseCode(String value) {
            this.supplierResponseCode = value;
        }

        /**
         * Gets the value of the merchantAccountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMerchantAccountNumber() {
            return merchantAccountNumber;
        }

        /**
         * Sets the value of the merchantAccountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMerchantAccountNumber(String value) {
            this.merchantAccountNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ReferenceNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CardDeploymentID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CardUsageResult {

        @XmlAttribute(name = "ResponseCode")
        protected String responseCode;
        @XmlAttribute(name = "ReferenceNbr")
        protected String referenceNbr;
        @XmlAttribute(name = "CardDeploymentID")
        protected String cardDeploymentID;

        /**
         * Gets the value of the responseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseCode() {
            return responseCode;
        }

        /**
         * Sets the value of the responseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseCode(String value) {
            this.responseCode = value;
        }

        /**
         * Gets the value of the referenceNbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceNbr() {
            return referenceNbr;
        }

        /**
         * Sets the value of the referenceNbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceNbr(String value) {
            this.referenceNbr = value;
        }

        /**
         * Gets the value of the cardDeploymentID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardDeploymentID() {
            return cardDeploymentID;
        }

        /**
         * Sets the value of the cardDeploymentID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardDeploymentID(String value) {
            this.cardDeploymentID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05/beta}PaymentCardType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PaymentCard
        extends PaymentCardType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05/beta}UserNameGroup"/>
     *       &lt;attribute name="SupplierID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MerchantAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PSP_HostedID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SignatureKey" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RoutingDetail {

        @XmlAttribute(name = "SupplierID", required = true)
        protected String supplierID;
        @XmlAttribute(name = "MerchantAccountNumber")
        protected String merchantAccountNumber;
        @XmlAttribute(name = "PSP_HostedID")
        protected String pspHostedID;
        @XmlAttribute(name = "SignatureKey")
        protected String signatureKey;
        @XmlAttribute(name = "UserName")
        protected String userName;
        @XmlAttribute(name = "Password")
        protected String password;

        /**
         * Gets the value of the supplierID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierID() {
            return supplierID;
        }

        /**
         * Sets the value of the supplierID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierID(String value) {
            this.supplierID = value;
        }

        /**
         * Gets the value of the merchantAccountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMerchantAccountNumber() {
            return merchantAccountNumber;
        }

        /**
         * Sets the value of the merchantAccountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMerchantAccountNumber(String value) {
            this.merchantAccountNumber = value;
        }

        /**
         * Gets the value of the pspHostedID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPSPHostedID() {
            return pspHostedID;
        }

        /**
         * Sets the value of the pspHostedID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPSPHostedID(String value) {
            this.pspHostedID = value;
        }

        /**
         * Gets the value of the signatureKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignatureKey() {
            return signatureKey;
        }

        /**
         * Sets the value of the signatureKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignatureKey(String value) {
            this.signatureKey = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

    }

}
