//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 12:59:01 PM CDT 
//


package com.sabre.hospitality.domain.payments.v300;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Outbound" type="{http://www.opentravel.org/OTA/2003/05/beta}RailJourneyType" minOccurs="0"/>
 *         &lt;element name="Return" type="{http://www.opentravel.org/OTA/2003/05/beta}RailJourneyType"/>
 *         &lt;element name="ProviderInfo" type="{http://www.opentravel.org/OTA/2003/05/beta}ProviderInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AgreementNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReferenceNbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RailType", propOrder = {
    "outbound",
    "_return",
    "providerInfo"
})
public class RailType {

    @XmlElement(name = "Outbound")
    protected RailJourneyType outbound;
    @XmlElement(name = "Return", required = true)
    protected RailJourneyType _return;
    @XmlElement(name = "ProviderInfo")
    protected ProviderInfoType providerInfo;
    @XmlAttribute(name = "AgreementNbr")
    protected String agreementNbr;
    @XmlAttribute(name = "ReferenceNbr")
    protected String referenceNbr;

    /**
     * Gets the value of the outbound property.
     * 
     * @return
     *     possible object is
     *     {@link RailJourneyType }
     *     
     */
    public RailJourneyType getOutbound() {
        return outbound;
    }

    /**
     * Sets the value of the outbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link RailJourneyType }
     *     
     */
    public void setOutbound(RailJourneyType value) {
        this.outbound = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link RailJourneyType }
     *     
     */
    public RailJourneyType getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link RailJourneyType }
     *     
     */
    public void setReturn(RailJourneyType value) {
        this._return = value;
    }

    /**
     * Gets the value of the providerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderInfoType }
     *     
     */
    public ProviderInfoType getProviderInfo() {
        return providerInfo;
    }

    /**
     * Sets the value of the providerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderInfoType }
     *     
     */
    public void setProviderInfo(ProviderInfoType value) {
        this.providerInfo = value;
    }

    /**
     * Gets the value of the agreementNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementNbr() {
        return agreementNbr;
    }

    /**
     * Sets the value of the agreementNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementNbr(String value) {
        this.agreementNbr = value;
    }

    /**
     * Gets the value of the referenceNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNbr() {
        return referenceNbr;
    }

    /**
     * Sets the value of the referenceNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNbr(String value) {
        this.referenceNbr = value;
    }

}
